### PR TITLE
Make NLLB pods tolerate NoExecute taints

### LINKED ISSUE #6955: NLLB on NoExecute-tainted nodes
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.34.2+k0s.0

### What happened?

I'm using a NoExecute taint on a subset of my nodes in a cluster to reserve them for specific workloads. K0s starts the nllb pod on these nodes, but k8s immediately evicts the pods due to the untolerated NoExecute taint. Since these are static pods, the eviction of the apiserver pod objects doesn't really have an effect, but it does trigger alerts in my cluster regarding pods staying in terminating state for too long.

### Steps to reproduce

1. Deploy a worker with any custom NoExecute taint and nllb enabled
2. check the kube-system namespace for the nllb pod of that node, it should be Terminating.

### Additional context

Only workaround I see currently would be to use a NoSchedule taint instead, but I haven't tested that yet.

### PR DESCRIPTION
**Pull request by pschichtel**
## Description

I introduced a toleration for all NoExecute taints on the static nllb pod as to prevent kubernetes from trying to evict the pod, which it can't do anyway.

Fixes #6955

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [X] Manual test
- [ ] Auto test added

## Checklist

- [X] My code follows the style [guidelines](https://docs.k0sproject.io/head/contributors/) of this project
- [X] My commit messages are [signed-off](https://docs.k0sproject.io/head/contributors/github_workflow/)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by pschichtel** [comment]
As mentioned in #6955, this can be easily reproduced by tainting any node in a cluster with any custom NoExecute taint. Without the fix, the nllb pod stays in Pending or Terminating, with the fix it becomes running. I've rolled this change out to a cluster without any issues so far.

File: pkg/component/worker/nllb/envoy.go [hunk 1]
```diff
@@ -303,6 +303,11 @@ func makePodManifest(params *envoyParams, podParams *envoyPodParams) corev1.Pod
 					},
 				}},
 			},
+			// without this kubernetes tries to evict the mirror pod on NoExecute-tainted nodes
+			Tolerations: []corev1.Toleration{{
+				Effect:   corev1.TaintEffectNoExecute,
```
Comment (twz123) [inline pkg/component/worker/nllb/envoy.go]: I wonder if we should bluntly tolerate _all_ taints, instead of _only_ the NoExecute taint... WDYT?

```suggestion
```

Comment (pschichtel) [reply pkg/component/worker/nllb/envoy.go]: Is that an option? I thought you have to at least specify an effect

Comment (pschichtel) [reply pkg/component/worker/nllb/envoy.go]: I haven't tested it, but I don't think NoSchedule or PreferNoSchedule have an impact, since static pods bypass the scheduler anyway

Comment (twz123) [reply pkg/component/worker/nllb/envoy.go]: It is: https://github.com/k0sproject/k0s/blob/v1.34.3+k0s.0/pkg/component/controller/konnectivityagent.go#L261-L262

**Comment by pschichtel** [comment]
> We could add priorityClassName: system-node-critical, as well.

I thought I read in the kubernetes documentation that static pods implicitly have system-node-critical, but I can't find it again, maybe I'm mistaken. It would be a trivial addition, but as you say, don't think it has an impact anyway. Even if kubernetes decides to evict a static pod, it doesn't actually do anything. This entire change is technically just a "cosmetic fix"

File: pkg/component/worker/nllb/envoy.go (hunk 1 above)
Comment (pschichtel) [reply pkg/component/worker/nllb/envoy.go]: ok then, let's do that.
