### PR TITLE
Use "object name safe" hostnames for leases and autopilot

### LINKED ISSUE #2011: Cluster Deployment using Hostnames with Capitial Letters Breaks during Konnectivity Service Installation Stage
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

1.24.3+k0s.0

### Platform

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
Architecture:   x86_64
Hostname:       renegade-VB <-- IMPORTANT

---

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
Architecture:   aarch64
Hostname:       renegade-desktop
```

### What happened?

When attempting to install a K0s Cluster using Hosts with capital letters in their Hostnames, installation will succeed, and pods will be schedulable. However, it is not possible to retrieve logs from pods, nor to exec into them, nor is it possible to port-forward any services.

### Steps to reproduce

1. Create a Multi-Node Cluster with at least one Host using capital letters in their Hostname.
2. Wait for the installation to fully apply.
3. Attempt to exec into a pod, or get the logs from a pod, or to port-forward a Service.

### Expected behavior

A Multi-Node Cluster should be capable of integrating Hosts without the requirement that their Hostname is lowercase.

### Actual behavior

When attempting any of the aforementioned three activities (retrieve logs from pods, exec into them, port-forward any services), they are all met with the same error:
```shell
/var/run/k0s/konnectivity-server/konnectivity-server.sock: connect: no such file or directory
``` 

And true enough, the `/var/run/k0s/konnectivity-server/` does exist:
```shell
$ ls -lAuhF /var/run/k0s/
total 36K
drwx--x--x 5 root                root  100 Aug  8 18:33 containerd/
-rw-r--r-- 1 root                root    5 Aug  8 18:33 containerd.pid
srw-rw---- 1 root                root    0 Aug  8 18:33 containerd.sock=
srw-rw---- 1 root                root    0 Aug  8 18:33 containerd.sock.ttrpc=
-rw-r--r-- 1 root                root    5 Aug  8 18:33 etcd.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 k0s-control-api.pid
-rwxr-xr-x 1 root                root 2.4K Aug  8 18:33 k0s.yaml*
-rw-r--r-- 1 root                root    5 Aug  8 18:33 konnectivity.pid
drwxr-xr-x 2 konnectivity-server root   60 Aug  8 18:33 konnectivity-server/
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kube-apiserver.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kube-controller-manager.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kubelet.pid
-rw-r--r-- 1 root                root    5 Aug  8 18:33 kube-scheduler.pid
srwxr-xr-x 1 root                root    0 Aug  8 18:33 status.sock=
```

But there is nothing in the `/var/run/k0s/konnectivity-server/` folder itself:
```shell
$ ls -lAuhF /var/run/k0s/konnectivity-server/
total 0
```

### Screenshots and logs

_No response_

### Additional context

I did use K0sctl v0.13.0 to deploy the Multi-Node Cluster.

Seems to be related to the following issues:
- #1352 
- #1123 

This StackOverflow post actually convinced me to attempt changing my Hostname, and it worked after reinstalling the Cluster:
- [StackOverflow Post](https://stackoverflow.com/a/72095755/10884550)

### PR DESCRIPTION
**Pull request by jnummelin**
Hosts with capital letters breaks these currently as kube objects cannot have capitals in the names of the objects.

The cases this fixes are those where we have not been able to create the corresponding objects at all and thus we do not have to do any cleanup etc..

Signed-off-by: Jussi Nummelin <jnummelin@mirantis.com>

## Description

Fixes #2011 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pkg/component/controller/controllersleasecounter.go [hunk 1]
```diff
@@ -56,7 +57,8 @@ func (l *K0sControllersLeaseCounter) Run(ctx context.Context) error {
 	}
 
 	// hostname used to make the lease names be clear to which controller they belong to
-	holderIdentity, err := os.Hostname()
+	// follow kubelet convention for naming so we e.g. use lowercase hostname etc.
+	holderIdentity, err := nodeutil.GetHostname("")
```
Comment (twz123) [inline pkg/component/controller/controllersleasecounter.go:61]: What about the "override-hostname" stuff? Are we ignoring that?

**Review by twz123 — DISMISSED** [review]

File: pkg/component/controller/controllersleasecounter.go (hunk 1 above)
Comment (jnummelin) [reply pkg/component/controller/controllersleasecounter.go:61]: Yes, all this stuff is happening on controllers only and "override-hostname" is for kubelet.

**Review by twz123 — APPROVED** [review]
