### PR TITLE
Delay join token parsing on worker until it is known that it is needed

### LINKED ISSUE #7202: Join token is now parsed on worker when not needed
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
any
```

### Version

v1.35.1+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
not relevant
</pre>
</details>

### What happened?

PR #6766 changed the order of handling join tokens on workers in a way that makes it now parse the token file when it's not needed because the node has already joined. Invalid token file contents now make an already joined k0s worker crash on restart.

k0sctl overwrites the token file after join and it becomes invalid. Since v1.35 k0s now fails to restart with the dummy token file (or a non-existent one?).

### Steps to reproduce

1. setup a k0s cluster and start it
2. overwrite the token file with some random text on a worker
3. restart k0s on the worker

### Expected behavior

k0s restarts cleanly

### Actual behavior

k0s errors out with `Error: failed to decode join token: illegal base64 data at input byte 0`

### Screenshots and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kke**
## Description

Fixes #7202 

Delays the parsing of join tokens on workers until it is known that the node needs to join and a token is needed.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [X] Manual test
- [X] Auto test added

## Checklist

- [X] My code follows the style [guidelines](https://docs.k0sproject.io/head/contributors/) of this project
- [X] My commit messages are [signed-off](https://docs.k0sproject.io/head/contributors/github_workflow/)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

File: cmd/internal/tokendata.go [hunk 1]
```diff
@@ -61,7 +61,7 @@ func GetTokenData(tokenArg, tokenFile string) (string, error) {
 		problem = "is empty"
 	}
 	if problem != "" {
-		return "", fmt.Errorf("token file %q %s"+
+		return "", fmt.Errorf(`token file "%s" %s`+
```
Comment (kke) [inline cmd/internal/tokendata.go:64]: %q messes up file paths on windows
