### PR TITLE
fix: kernel modules not enabled, modprobe is not executed

### LINKED ISSUE #5579: Linux kernel modules are not enabled, modprobe command not executed
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell

```

### Version

_No response_

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

Linux kernel modules are not being enabled like you think they are.

exec.Command returns the Cmd type. It does not execute it

https://pkg.go.dev/os/exec#Command

See the following code:

https://github.com/k0sproject/k0s/blob/fb9fb09cdbea20afa64fbb0218c7eca0ac0a61c7/pkg/component/worker/kernelsetup_linux.go#L45-L50

### Steps to reproduce

1.
2.
3.

### Expected behavior

_No response_

### Actual behavior

_No response_

### Screenshots and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emosbaugh**
## Description

Fixes #5579

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [ ] Auto test added

## Checklist

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by jnummelin — APPROVED** [review]

**Comment by emosbaugh** [comment]
I am unsure why the arm airgap tests are failing

**Comment by jnummelin** [comment]
Seems there's something corrupted in the cached airgap image bundle:
```
time="2025-02-12 21:10:02" level=error msg="Failed to load OCI bundle /var/lib/k0s/images/bundle.tar" component=OCIBundleReconciler error="failed to process OCI bundle: can't import bundle: failed to ingest \"blobs/sha256/fc10de082a9c2d373dcfe31ce281c9ff20bac43a93968f734d8bcb3533b6f075\": failed to read expected number of bytes: unexpected EOF"
```

File: pkg/component/worker/kernelsetup_linux.go [hunk 1]
```diff
@@ -43,9 +43,9 @@ func hasFilesystem(filesystem string) bool {
 }
 
 func modprobe(module string) {
-	err := exec.Command("modprobe", module)
+	out, err := exec.Command("modprobe", module).CombinedOutput()
 	if err != nil {
-		logrus.Warnf("failed to load %s kernel module: %s", module, err)
+		logrus.Warnf("failed to load %s kernel module: %s, out=%q", module, err.Error(), string(out))
```
Comment (twz123) [inline pkg/component/worker/kernelsetup_linux.go:48]: No need to cast a byte array to string when using %s or %q in the format string.

```suggestion
		logrus.WithError(err).Warnf("failed to load kernel module %s: %s, module, out)
```

**Review by twz123 — DISMISSED** [review]

**Review by twz123 — APPROVED** [review]
