### PR TITLE
Fix k0s restore location

### LINKED ISSUE #2459: After restoring，controller exec “k0s ctr version” can not get containerd server info
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Version

v1.25.2+k0s.0

### Sysinfo

Machine ID: "b820f275aba5719db041d43557f391302a29df482a55f4b96fcac217338b35e4" (from machine) (pass)
Total memory: 3.8 GiB (pass)
Disk space available for /var/lib/k0s: 78.7 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.0-53-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  Executable in path: modprobe: /usr/sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 1 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (pass)
    cgroup controller "freezer": available (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)

### What happened?

After restoring，controller exec “k0s ctr version” can not get containerd server info 

### Steps to reproduce

1. install 
    executes `k0sctl apply --disable-telemetry -c k0sctl_deploy_tmp/k0sctl_deploy.yml` on k0sctl_node 

`
# k0sctl_deploy.yml
---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.122.144 
      user: root
      port: 22
      keyPath: /root/.ssh/id_ed25519
    role: controller+worker
    installFlags:
      - --no-taints
    uploadBinary: true
    k0sBinaryPath: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s"
    files:
      - name: bundle-file
        src: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s-airgap-bundle"
        dstDir: /var/lib/k0s/images/
        perm: 0666

  - ssh:
      address: 192.168.122.216  
      user: root
      port: 22
      keyPath: /root/.ssh/id_ed25519
    role: worker
    uploadBinary: true
    k0sBinaryPath: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s"
    files:
      - name: bundle-file
        src: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s-airgap-bundle"
        dstDir: /var/lib/k0s/images/
        perm: 0666

  - ssh:
      address: 192.168.122.46  
      user: root
      port: 22
      keyPath: /root/.ssh/id_ed25519
    role: worker
    uploadBinary: true
    k0sBinaryPath: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s"
    files:
      - name: bundle-file
        src: "/root/桌面/k0s/issue_32_25/cloud-service-k0s-deploy/ansible/.k0s_dependencies/k0s-airgap-bundle"
        dstDir: /var/lib/k0s/images/
        perm: 0666

  k0s:
    version: v1.25.2+k0s.0
    dynamicConfig: false

`

2. backup
    `k0s backup --save-path=/root`

3. restore 
  `
root@k0s-master:/var/lib/k0s#  k0s stop
root@k0s-master:/var/lib/k0s#  mv etcd etcd-bak
root@k0s-master:/var/lib/k0s# k0s restore /root/k0s_backup_2022-11-25T10_59_15_000Z.tar.gz
root@k0s-master:/var/lib/k0s#  k0s start
`

4. test k0s containerd version
`
root@k0s-master:/var/lib/k0s# k0s ctr version
Client:
  Version:  1.6.8
  Revision: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
  Go version: go1.19.1

Error: failed to dial "/run/k0s/containerd.sock": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix:///run/k0s/containerd                         .sock: timeout"
Usage:
  k0s ctr [flags]

Flags:
  -h, --help   help for ctr

root@k0s-master:/var/lib/k0s# 
`

### Expected behavior

`
root@k0s-master:~# k0s ctr version
Client:
  Version:  1.6.8
  Revision: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
  Go version: go1.19.1

Server:
  Version:  1.6.8
  Revision: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
  UUID: 4e85d06f-822b-4514-acee-fe54b79c8593
root@k0s-master:~#

`

### Actual behavior

_No response_

### Screenshots and logs
`journalctl -u k0scontroller `
[journalctl.log](https://github.com/k0sproject/k0s/files/10111607/journalctl.log)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description

Prior to this patch k0s retore would restore some files to a wrong location. This patch solves this issue.

Fixes #2459
Find more technical details of what was wrong in the issue.

Signed-off-by: Juan Luis de Sousa-Valadas Castaño <jvaladas@mirantis.com>

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [x] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: internal/pkg/dir/dir_test.go [hunk 1]
```diff
@@ -57,3 +59,56 @@ func TestInit(t *testing.T) {
...
+	}
+
+	// Test that copying actually works
+	dst = t.TempDir()
+	expectedDirs := []string{"dir1/", "dir2/", "dir2/dir1/", "dir2/dir2/"}
+	expectedFiles := []string{"dir1/file1", "dir1/file2", "dir2/file1", "dir2/dir2/file1"}
+
+	for _, dir := range expectedDirs {
+		p := path.Join(src, dir)
+		err = exec.Command("mkdir", p).Run()
```
Comment (twz123) [inline internal/pkg/dir/dir_test.go:87]: [`os.MkdirAll`](https://pkg.go.dev/os#MkdirAll) as an alternative?

File: internal/pkg/dir/dir_test.go [hunk 2]
```diff
@@ -57,3 +59,56 @@ func TestInit(t *testing.T) {
...
+		t.Fatalf("Unable to copy empty dir: %v", err)
+	}
+
+	//rmdir will fail if the directory has anything at all
+	err = exec.Command("rmdir", path.Join(dst, srcDirname)).Run()
+	if err != nil {
+		t.Fatalf("Unable to remove supposedly empty dir: %v", err)
+	}
+
+	// Test that copying actually works
```
Comment (twz123) [inline internal/pkg/dir/dir_test.go:80]: To add a bit more structure besides the comments, you could put the different tests either into their own test functions à la `TestCopy_EmptyDirs` and `TestCopy_FilesAndDirs` (or similar), or run them as subtests using `t.Run("EmptyDirs", func (t *testing.T) { ... })`.

File: internal/pkg/dir/dir_test.go [hunk 3]
```diff
@@ -57,3 +59,56 @@ func TestInit(t *testing.T) {
...
+		if err != nil {
+			t.Fatalf("Unable to create directory %s: %v", p, err)
+		}
+	}
+
+	for _, file := range expectedFiles {
+		p := path.Join(src, file)
+		err = exec.Command("touch", p).Run()
+		if err != nil {
+			t.Fatalf("Unable to file directory %s: %v", p, err)
```
Comment (twz123) [inline internal/pkg/dir/dir_test.go:97]: That doesn't sound quite right? 😀

File: internal/pkg/dir/dir_test.go [hunk 4]
```diff
@@ -57,3 +59,56 @@ func TestInit(t *testing.T) {
...
+		p := path.Join(src, dir)
+		err = exec.Command("mkdir", p).Run()
+		if err != nil {
+			t.Fatalf("Unable to create directory %s: %v", p, err)
+		}
+	}
+
+	for _, file := range expectedFiles {
+		p := path.Join(src, file)
+		err = exec.Command("touch", p).Run()
```
Comment (twz123) [inline internal/pkg/dir/dir_test.go:95]: Do you want to create those files? I'd just do sth. like `os.WriteFile(p, []byte{}, 0644)` instead.

File: internal/pkg/dir/dir_test.go [hunk 5]
```diff
@@ -57,3 +59,56 @@ func TestInit(t *testing.T) {
...
+		t.Fatalf("Unable to copy dir with contents: %v", err)
+	}
+
+	destPath := path.Join(dst, srcDirname)
+	for _, file := range expectedFiles {
+		p := path.Join(destPath, file)
+		_, err = os.Stat(p)
+		if err != nil {
+			t.Fatalf("File %s does not seem to exist: %v", file, err)
+		}
```
Comment (twz123) [inline internal/pkg/dir/dir_test.go:112]: There's also [`assert.FileExists`](https://pkg.go.dev/github.com/stretchr/testify/assert#FileExists) (and `require.FileExists`).

File: inttest/backup/backup_test.go [hunk 6]
```diff
@@ -95,15 +97,17 @@ func (s *BackupSuite) TestK0sGetsUp() {
...
+	s.Reset(s.ControllerNode(1))
 
 	s.Require().NoError(s.restoreFunc())
-	s.Require().NoError(s.InitController(0))
+	s.Require().NoError(s.InitController(0, "--enable-worker"))
 	s.Require().NoError(s.WaitJoinAPI(s.ControllerNode(0)))
 
 	// Join the second controller as normally
-	s.Require().NoError(s.InitController(1, token))
+	s.Require().NoError(s.InitController(1, token, "--enable-worker"))
```
Comment (twz123) [inline inttest/backup/backup_test.go:110]: Just a tiny nit, but I'd place flags first, then the args... 
```suggestion
	s.Require().NoError(s.InitController(1, "--enable-worker", token))
```

File: inttest/backup/backup_test.go [hunk 7]
```diff
@@ -95,15 +97,17 @@ func (s *BackupSuite) TestK0sGetsUp() {
 	s.Require().NoError(s.StopController(s.ControllerNode(0)))
 	_ = s.StopController(s.ControllerNode(1)) // No error check as k0s might have actually exited since etcd is not really happy
 
-	s.Require().NoError(s.Reset(s.ControllerNode(0)))
-	s.Require().NoError(s.Reset(s.ControllerNode(1)))
+	// Reset will return an error because after starting the controller with --enable-worker
+	// k0s reset will try to delete /var/lib/k0s, which is not possible because it's a volume in docker.
+	s.Reset(s.ControllerNode(0))
+	s.Reset(s.ControllerNode(1))
```
Comment (twz123) [inline inttest/backup/backup_test.go:103]: I'd use an underscore. (Mostly to satisfy linters).


```suggestion
	_ = s.Reset(s.ControllerNode(0))
	_ = s.Reset(s.ControllerNode(1))
```

File: inttest/backup/backup_test.go [hunk 8]
```diff
@@ -155,6 +161,25 @@ func (s *BackupSuite) makeSnapshot(kc *kubernetes.Clientset) snapshot {
...
+func (s *BackupSuite) VerifyFileSystemRestore() error {
+	ssh, err := s.SSH(s.ControllerNode(0))
+	if err != nil {
+		return err
+	}
+	defer ssh.Disconnect()
+
+	// Checking for containerd should be enough given https://github.com/k0sproject/k0s/issues/2420
+	// containerd may take a bit to start so we want to retry a few times
+	for i := 0; i < 18; i++ {
```
Comment (twz123) [inline inttest/backup/backup_test.go:173]: You might also have a look at [`assert.Eventually`](https://pkg.go.dev/github.com/stretchr/testify/assert#Eventually).

File: internal/pkg/dir/dir_test.go [hunk 9]
```diff
@@ -57,3 +59,56 @@ func TestInit(t *testing.T) {
...
+
+	// Test that empty directories don't copy anything
+	dst := t.TempDir()
+	err := Copy(src, dst)
+	if err != nil {
+		t.Fatalf("Unable to copy empty dir: %v", err)
+	}
+
+	//rmdir will fail if the directory has anything at all
+	err = exec.Command("rmdir", path.Join(dst, srcDirname)).Run()
```
[the remark this answers is not in the document]
Comment (kke) [reply internal/pkg/dir/dir_test.go:75]: Maybe `os.Remove` instead of read :)

File: internal/pkg/dir/dir.go [hunk 10]
```diff
@@ -59,9 +59,5 @@ func Init(path string, perm os.FileMode) error {
 // Copy copies the content of a folder
 func Copy(src string, dst string) error {
 	cmd := exec.Command("cp", "-r", src, dst)
```
[the remark this answers is not in the document]
Comment (juanluisvaladas) [reply internal/pkg/dir/dir.go:61]: Good point, I will fix this as well.
Anyway I already changed this function and it wasn't even related to the issue.

File: internal/pkg/dir/dir_test.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (twz123) [reply internal/pkg/dir/dir_test.go:75]: Depends on what this check is supposed to prove. It looks like it is just to prove that the directory is empty, taking advantage of the fact that `rmdir` fails for non-empty directories. That's why I suggested `ReadDir` instead of `Remove`.

File: internal/pkg/dir/dir_test.go [hunk 11]
```diff
@@ -57,3 +59,56 @@ func TestInit(t *testing.T) {
...
+func TestCopy(t *testing.T) {
+	src := t.TempDir()
+	srcDirname := path.Base(src)
+
+	// Test that empty directories don't copy anything
+	dst := t.TempDir()
+	err := Copy(src, dst)
+	if err != nil {
+		t.Fatalf("Unable to copy empty dir: %v", err)
+	}
```
[the remark this answers is not in the document]
Comment (juanluisvaladas) [reply internal/pkg/dir/dir_test.go:72]: Good point, that's much better.

Since I was modifying this file I also changed the other tests in this file for consistency.

File: inttest/backup/backup_test.go [hunk 12]
```diff
@@ -155,6 +161,25 @@ func (s *BackupSuite) makeSnapshot(kc *kubernetes.Clientset) snapshot {
...
+	defer ssh.Disconnect()
+
+	// Checking for containerd should be enough given https://github.com/k0sproject/k0s/issues/2420
+	// containerd may take a bit to start so we want to retry a few times
+	checkPID := func() bool {
+		_, err = ssh.ExecWithOutput(s.Context(), "/bin/pidof /var/lib/k0s/bin/containerd")
+		return err == nil
+	}
+
+	assert.Eventuallyf(s.T(), checkPID, 18*time.Second, 10*time.Second,
```
Comment (twz123) [inline inttest/backup/backup_test.go:178]: 1. Shouldn't this be 180 seconds?
2. Suites support assertions out of the box

```suggestion
	s.Eventuallyf(checkPID, 180*time.Second, 10*time.Second,
```

**Review by twz123 — DISMISSED** [review]

File: inttest/backup/backup_test.go (hunk 12 above)
Comment (juanluisvaladas) [reply inttest/backup/backup_test.go]: D'oh! yes it should. I broke the tests on purpose to test that they actually worked and I forgot about this one. Sorry.

**Review by twz123 — APPROVED** [review]
