### PR TITLE
Kuberouter IPv6 network conformance tests

### LINKED ISSUE #6262: Network conformance fails on kuberouter single stack ipv6
Tests e2e test fails with: 

  [FAIL] [sig-network] Proxy version v1 [It] should proxy through a service and a pod [Conformance] [sig-network, Conformance]
  k8s.io/kubernetes/test/e2e/network/proxy.go:317
  [FAIL] [sig-network] DNS [It] should support configurable pod DNS nameservers [Conformance] [sig-network, Conformance]
  k8s.io/kubernetes/test/e2e/network/dns.go:466
  [FAIL] [sig-network] DNS [It] should provide DNS for pods for Subdomain [Conformance] [sig-network, Conformance]
  k8s.io/kubernetes/test/e2e/network/dns_common.go:476
  [FAIL] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: udp [NodeConformance] [Conformance] [sig-network, NodeConformance, Conformance]
  k8s.io/kubernetes/test/e2e/common/network/networking.go:72
  [FAIL] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: http [NodeConformance] [Conformance] [sig-network, NodeConformance, Conformance]
  k8s.io/kubernetes/test/e2e/common/network/networking.go:72

### PR DESCRIPTION
**Pull request by juanluisvaladas**
Implement network conformance tests for IPv6 on kube-router

## Description

Fixes #6262

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [x] Auto test added

## Checklist

- [ ] My code follows the style [guidelines](https://docs.k0sproject.io/head/contributors/) of this project
- [ ] My commit messages are [signed-off](https://docs.k0sproject.io/head/contributors/github_workflow/)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
The test stopped being flaky and started failing consistently so I'm actively working on it right now. The failing tests are:

1.  [sig-network] DNS should provide DNS for pods for Subdomain [Conformance]
2. [sig-network] DNS should support configurable pod DNS nameservers [Conformance]

Both tests fail on test/e2e/network/dns.go

**Comment by juanluisvaladas** [comment]
I'll wait for https://github.com/k0sproject/k0s/pull/7458 since there are relevant changes in the conformance tests regarding DNS. after that I'll rebase and make it ready to merge.

File: inttest/network-conformance/network_test.go [hunk 1]
```diff
@@ -86,6 +86,9 @@ func (s *networkSuite) TestK0sGetsUp() {
 	s.T().Log("waiting to see CNI pods ready for", daemonSetName)
 	s.NoErrorf(common.WaitForDaemonSet(s.Context(), kc, daemonSetName, metav1.NamespaceSystem), "%s did not start", daemonSetName)
 
+	s.T().Log("waiting for konnectivity-agent to be ready")
```
Comment (juanluisvaladas) [inline inttest/network-conformance/network_test.go:89]: If we don't add this wait on kube-router IPv6  it becomes super flaky.

The reason why this doesn't happen in IPv4 is because pulling kube-router takes significantly longer than pulling konnectivity and the reason why it doesn't happen on calico is because calico takes much longer to become ready.

**Review by jnummelin — APPROVED** [review]
