### PR TITLE
Make "k0s config validate" display errors

### LINKED ISSUE #3563: "k0s config validate" is silent
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

_No response_

### Version

v1.28.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
doesn't matter
</pre>
</details>

### What happened?

```console
$ echo hello > k0s.yaml
$ k0s config validate --config k0s.yaml
$ k0s controller --config k0s.yaml
Error: failed to load node config: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1beta1.config
$ k0s config validate --config k0s.yaml || echo "no bueno"
no bueno
```

So, exit status seems to be correct but nothing is shown.

### Steps to reproduce

1. have a broken config
2. validate it using `k0s config validate`

### Expected behavior

```console
$ k0s config validate
Error: invalid node config: spec: extensions: can't create default storage class for external_storage
```

### Actual behavior

```console
$ k0s config validate
$
```

### Screenshots and logs

_No response_

### Additional context

Ref: https://github.com/k0sproject/k0sctl/pull/567

### PR DESCRIPTION
**Pull request by kke**
## Description

Makes `k0s config validate` display error messsages.

The reason was that `SilenceErrors` was `true`.

Fixes #3563 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [X] Auto test added

## Checklist:

- [X] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [X] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

File: cmd/config/validate.go [hunk 1]
```diff
@@ -59,13 +59,18 @@ func NewValidateCmd() *cobra.Command {
...
+					fmt.Fprintln(stderr, "-", e.Error())
+				}
+				cmd.SilenceErrors = true
+				return errors.Join(errs...)
 			}
 
 			return nil
 		},
-		SilenceUsage:  true,
-		SilenceErrors: true,
```
Comment (twz123) [inline cmd/config/validate.go:68]: Wouldn't removing this line have been enough?

Comment (kke) [reply cmd/config/validate.go:68]: Mostly yes, for testability the os.Stdin change also. The error formatting seems to be unnecessary since errors.Join already adds newlines.

**Review by twz123 — DISMISSED** [review]

**Review by twz123 — APPROVED** [review]
