### PR TITLE
Fix kubelet dual stack kubelet flags

### LINKED ISSUE #7464: kubelet-extra-args needs a few args to get proper ordering
kuberouter needs a mix of extraArgs and rawArgs to force v6 primary:
*   ` --node-ip=<IPv6>,<IPv4>` to let pods get v6 first
*  ` --address=::` to bind on v6 rather than v4
*  `--cluster-dns=<IPv6>,<IPv4>` otherwise only IPv4 is set

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description

This commit does three different things:
1- Move the method `PrimaryAddressFamily` from `ClusterConfig` to `ClusterSpec`. This is a preparation for including the `primaryAddressFamily` in the `workerProfile`
2- Add a `PrimaryAddressFamily` to the `workerProfile`
3- Set kubelet's node-ip to a value according to the `primaryAddressFamily`.

Fixes #7464

#7464 mentions that they need to set several flags, but we only need to set the node-ip. The remaining flagsare not required as we're not filling them and kubelet is inferring them from the node-ip.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [x] Auto test added

## Checklist

- [x] My code follows the style [guidelines](https://docs.k0sproject.io/head/contributors/) of this project
- [x] My commit messages are [signed-off](https://docs.k0sproject.io/head/contributors/github_workflow/)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by twz123 — APPROVED** [review]

**Comment by juanluisvaladas** [comment]
This is annoying... We cannot obtain PrimaryAddressFamily with dynamic config because `clusterconfig.spec.api` are removed... I'll address this in a separate PR.

**Review by twz123 — COMMENTED** [review]
Okay, then let's wait for these changes.

**Comment by juanluisvaladas** [comment]
Fixed in https://github.com/k0sproject/k0s/pull/7494

File: pkg/apis/k0s/v1beta1/clusterconfig_types.go [hunk 1]
```diff
@@ -482,7 +482,7 @@ func (c *ClusterConfig) Validate() (errs []error) {
 // - Network.PrimaryAddressFamily
 // - Install
 func (c *ClusterConfig) GetClusterWideConfig() *ClusterConfig {
-	primaryAF := c.PrimaryAddressFamily()
+	primaryAF := c.Spec.PrimaryAddressFamily()
```
Comment (juanluisvaladas) [inline pkg/apis/k0s/v1beta1/clusterconfig_types.go:485]: @twz123 I had to do a rebase after merging https://github.com/k0sproject/k0s/pull/7494. This line is the only thing that had to be changed.

**Review by jnummelin — APPROVED** [review]
