### PR TITLE
Make Supervisor kill pidFile before Start

### LINKED ISSUE #2537: Supervisor will start the process of a component even if the process was started
This happens on the main branch and I believe it has always been like this, I will fix this soon.

## How to reproduce

```
# cat /run/k0s/containerd.pid 
803
# ps aux | grep -e /usr/local/bin/k0s -e /var/lib/k0s/bin/containerd
root         783  0.1  7.3 797716 72336 ?        Ssl  19:47   0:00 /usr/local/bin/k0s worker --kubelet-extra-args=--node-ip=192.168.122.74
root         803  0.2  4.1 754680 40800 ?        Sl   19:47   0:00 /var/lib/k0s/bin/containerd --root=/var/lib/k0s/containerd --state=/run/k0s/containerd --address=/run/k0s/containerd.sock --log-level=info --config=/etc/k0s/containerd.toml
root         894  0.0  0.2   6208  2112 pts/0    S+   19:48   0:00 grep --color=auto -e /usr/local/bin/k0s -e /var/lib/k0s/bin/containerd
# kill -9 783
# # wait for the k0s to come up
# cat /run/k0s/containerd.pid 
2242
# ps aux | grep -e 803 -e 2242
root         803  0.5  5.1 756916 50832 ?        Sl   19:47   0:01 /var/lib/k0s/bin/containerd --root=/var/lib/k0s/containerd --state=/run/k0s/containerd --address=/run/k0s/containerd.sock --log-level=info --config=/etc/k0s/containerd.toml
root        2242  0.2  3.2 752604 31636 ?        Sl   19:52   0:00 /var/lib/k0s/bin/containerd --root=/var/lib/k0s/containerd --state=/run/k0s/containerd --address=/run/k0s/containerd.sock --log-level=info --config=/etc/k0s/containerd.toml
```
## Expected behavior

The process should not be started twice.
The supervisor should be smart enough to check if the PID exists. If it exists check if it's the same command and true kill it and start a new one.

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description

Prior to this commit the pidFiles were written but ignored. This avoids starting the same process twice which could be a problem.

The PR is marked as a draft because the tests need to be refactored because there is a lot of duplicate code. But other than that I'm quite happy with the current result

Fixes #2537

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [x] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by juanluisvaladas** [comment]
Uhg I hadn't thought about windows, how can I spin up a cluster with a windows machine?

File: pkg/supervisor/supervisor_nix.go [hunk 1]
```diff
@@ -0,0 +1,98 @@
+//go:build !windows
```
Comment (soider) [inline pkg/supervisor/supervisor_nix.go:1]: I think it is not necessary to have explicit build tags and the OS specific suffix in the filename. So probably having files supervisor_posix and supervisor_windows COULD work here :)

Btw, why do we have two `go:build` and `build:`? 
We can safely use only the one which works for the latest go version since we don't provide our code as a library.
Otherwise we have three different build constraint sources: filename, new style tag, old style tag and we need to keep them more or less in sync.

What do you think, if we try to have only one build tag style or even check, may be with a correct naming (_posix and _windows) it would not require tags at all?

**Review by soider — CHANGES_REQUESTED** [review]
Generally looks good, there is a minor suggestion to improve build tags handling.

File: pkg/supervisor/supervisor.go [hunk 2]
```diff
@@ -123,6 +127,14 @@ func (s *Supervisor) Supervise() error {
 		s.TimeoutRespawn = 5 * time.Second
 	}
 
+	_, err := os.Stat(s.PidFile)
+	if !os.IsNotExist(err) {
```
Comment (ncopa) [inline pkg/supervisor/supervisor.go:131]: This check is not necessary. We check the existence of the file when we open it.

File: pkg/supervisor/supervisor_nix.go [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+// maybeKillPidFile checks kills the process in the pidFile if it's has
+// the same binary as the supervisor's. This function does not delete
+// the old pidFile as this is done by the caller.
+func (s *Supervisor) maybeKillPidFile() error {
+	if s.ProcFSPath == "" {
+		s.ProcFSPath = "/proc"
+	}
+	pid, err := os.ReadFile(s.PidFile)
+	if err != nil {
+		return fmt.Errorf("failed to read pid file %s: %v", s.PidFile, err)
```
Comment (ncopa) [inline pkg/supervisor/supervisor_nix.go:75]: I think we could return nil if the error is IsNotExist.

File: pkg/supervisor/supervisor_nix.go [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+	}
+
+	p, err := strconv.Atoi(strings.TrimSuffix(string(pid), "\n"))
+	if err != nil {
+		return fmt.Errorf("failed to parse pid file %s: %v", s.PidFile, err)
+	}
+
+	if !s.isRunning(p) {
```
Comment (ncopa) [inline pkg/supervisor/supervisor_nix.go:83]: Keep in mind that the process could die directly after this check.

File: pkg/supervisor/supervisor_nix.go [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+
+// killPid signals SIGTERM to a PID and if it's still running after
+// s.TimeoutStop sends SIGKILL.
+func (s *Supervisor) killPid(pid int) error {
+	if s.KillFunction == nil {
+		s.KillFunction = syscall.Kill
+	}
+	// Kill the process pid
+	if err := s.KillFunction(pid, syscall.SIGTERM); err != nil {
+		return fmt.Errorf("failed to send SIGTERM to pid %d: %s", pid, err)
```
Comment (ncopa) [inline pkg/supervisor/supervisor_nix.go:44]: the process may already be dead, in which case kill will return [ESRCH](https://man7.org/linux/man-pages/man2/kill.2.html#ERRORS) error.

File: pkg/supervisor/supervisor_nix.go [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+	}
+
+	if err := s.KillFunction(pid, syscall.SIGKILL); err != nil {
+		return fmt.Errorf("failed to send SIGKILL to pid %d: %s", s.cmd.Process.Pid, err)
+	}
+	return nil
+}
+
+func (s *Supervisor) isRunning(pid int) bool {
+	_, err := os.Stat(filepath.Join(s.ProcFSPath, strconv.Itoa(pid)))
```
Comment (ncopa) [inline pkg/supervisor/supervisor_nix.go:62]: `s.KillFunction(pid, 0)` can also be used to test if process is running.

Comment (juanluisvaladas) [reply pkg/supervisor/supervisor_nix.go:62]: I like the idea of having the same code handling both the test and the real cases, however that's certainly cleaner and allows us to remove Supervisor.ProcFSPath...

File: pkg/supervisor/supervisor_nix.go (hunk 1 above)
Comment (juanluisvaladas) [reply pkg/supervisor/supervisor_nix.go:1]: > Btw, why do we have two go:build and build:?
Quite frankly, I just grepped and copied it from other places :) 

> I think it is not necessary to have explicit build tags and the OS specific suffix in the filename. So probably having files supervisor_posix and supervisor_windows COULD work here :)

Turns out _windows.go is respected by default but _posix.go / _unix.go is not :/ . Although _linux.go is honored.
I added the //build:  https://go-review.googlesource.com/c/go/+/389935 because I fear calling it _linux.go will break macOS and I don't really want to add yet another dummy file  for darwin...

**Comment by juanluisvaladas** [comment]
I'm still addressing the comments, this push is just to see if it fixes the windows builds.

**Comment by juanluisvaladas** [comment]
I believe all the concerns are addressed:
1- There are no sleeps in the tests
2- We verify for signal ESRCH errors
3- We don't run unnecessary checks

I tested it manually and seems fine. It's just missing checking for the env variable but I want the tests to run before implementing that so I'm still having this as a draft.

**Comment by juanluisvaladas** [comment]
Everything should be addressed now:
1- There are no sleeps in the tests
2- We verify for signal ESRCH errors
3- We don't run unnecessary checks
4- We verify cmdline and environ before killing.

File: pkg/supervisor/supervisor.go [hunk 7]
```diff
@@ -60,6 +64,8 @@ type Supervisor struct {
 	cancel         context.CancelFunc
 }
 
+const k0sManaged = "_K0S_MANAGED=yes"
```
Comment (mikhail-sakhnov) [inline pkg/supervisor/supervisor.go:67]: does the underscore have some meaning here?

Comment (juanluisvaladas) [reply pkg/supervisor/supervisor.go:67]: Not really. The underscore is there because it's the value we decided during the discussion in the call.

File: pkg/supervisor/supervisor_unix.go [hunk 8]
```diff
@@ -0,0 +1,126 @@
...
+	cmd := strings.Split(string(cmdline), "\x00")
+	if cmd[0] != s.BinPath {
+		return nil
+	}
+
+	//only kill process if it has the _KOS_MANAGED env set
+	env, err := os.ReadFile(filepath.Join(s.ProcFSPath, strconv.Itoa(p), "environ"))
+	if err != nil {
+		return fmt.Errorf("failed to read process %d environ: %v", p, err)
+	}
```
Comment (ncopa) [inline pkg/supervisor/supervisor_unix.go:118]: The process may be terminated after reading `cmdline`.
```suggestion
	if os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return fmt.Errorf("failed to read process %d environ: %v", p, err)
	}
```

**Review by ncopa — CHANGES_REQUESTED** [review]

**Comment by juanluisvaladas** [comment]
@mikhail-sakhnov I believe you were OK with the variable being called `_K0S_MANAGED=yes` because it's what was agreed on the call. Please let me know if that's OK with you or if you want to change it to `K0S_MANAGED=yes` instead. 

@ncopa I made a slight change in the function maybeKillPid and killPid. Now it checks for the name of the process and the environment variables right before killing the process.

**Comment by juanluisvaladas** [comment]
@mikhail-sakhnov I believe you were OK with the variable being called `_K0S_MANAGED=yes` because it's what was agreed on the call. Please let me know if that's OK with you or if you want to change it to `K0S_MANAGED=yes` instead. 

@ncopa I made a slight change in the function maybeKillPid and killPid. Now it checks for the name of the process and the environment variables right before killing the process.

File: pkg/supervisor/supervisor_windows.go [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+
+import (
+	"time"
+)
+
+// maybeKillPidFile checks kills the process in the pidFile if it's has
+// the same binary as the supervisor's. This function does not delete
+// the old pidFile as this is done by the caller.
+func (s *Supervisor) maybeKillPidFile(check <-chan time.Time, deadline <-chan time.Time) error {
+	s.log.Warnf("maybeKillPidFile is not implemented on Windows")
```
Comment (twz123) [inline pkg/supervisor/supervisor_windows.go:30]: I wonder why that is. There's still the possibility of sending `os.Kill` to terminate the process. Anyhow, we can address this later on.

Comment (juanluisvaladas) [reply pkg/supervisor/supervisor_windows.go:30]: I think it's worth merging this as is and merging your patch for this for several reasons:
1- I don't have a windows environment to properly test this and we need to get this merged ASAP because of the release.
2- Windows is broken at the moment anyway.
3- Your solution is almost implemented right now and it's a good implementation. Duplicating the effort seems unreasonable to me.

Anyway we need a way to get windows workers for our local environments.

**Review by ncopa — APPROVED** [review]
