### PR TITLE
Include inttest in make lint

### LINKED ISSUE #2940: make lint does not include inttest
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Issue

I  believe we can all agree without much discussion that it's a good idea to lint inttest and that it could help preventing some bugs in the tests themselves.

I checked the linting and I don't think anyone would argue about most stuff but, but there are 2 lint errors I think will need some discussion:

```
inttest/common/footloosesuite.go:323:53: context-as-argument: context.Context should be the first parameter of a function (revive)
func (s *FootlooseSuite) cleanupSuite(t *testing.T, ctx context.Context) {
                                                    ^
inttest/common/footloosesuite.go:401:53: context-as-argument: context.Context should be the first parameter of a function (revive)
func (s *FootlooseSuite) dumpNodeLogs(t *testing.T, ctx context.Context, node, dir string) {
```

If we want linting there are two options here:
1- We make an exception and remove the argument `context-as-argument` for inttest
2- We change the function so that context.Context is the first argument,

The convention is [**MOST** functions that use a Context **SHOULD** accept it as their first parameter](https://github.com/golang/go/wiki/CodeReviewComments#contextsl) (emphasis is mine). 
This makes sense to me to some extent but at the same time I think testing.T should go before the Context. Besides the convention says most and should so I understand it's a bit open to interpretation.

Anyway I don't feel very strongly about either option.

Of course we can keep without linting the tests but honestly I think it would be a mistake.

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description

This commit changes the Makefile so that inttest is linted and fixes all the linting errors.

Fixes #2940

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [x] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -215,7 +216,7 @@ lint: GOLANGCI_LINT_FLAGS ?=
 lint: .k0sbuild.docker-image.k0s go.sum codegen
 	hack/copyright.sh
 	CGO_ENABLED=0 $(GO) install github.com/golangci/golangci-lint/cmd/golangci-lint@v$(golangci-lint_version)
-	$(GO_ENV) golangci-lint run --verbose $(GOLANGCI_LINT_FLAGS) $(GO_DIRS)
+	$(GO_ENV) golangci-lint run --verbose $(GOLANGCI_LINT_FLAGS) $(GO_LINT_DIRS)
```
Comment (twz123) [inline Makefile:219]: I wonder if we should move all of this into .golangci.yml. This has the benefit of being consistent with IDE integrations then.

File: inttest/cnichange/cnichange_test.go [hunk 2]
```diff
@@ -44,11 +44,12 @@ func (s *CNIChangeSuite) TestK0sGetsUpButRejectsToChangeCNI() {
 	s.Require().NoError(err)
 
 	// Wait till we see kube-router DS created
-	watch.DaemonSets(kc.AppsV1().DaemonSets("kube-system")).
+	err = watch.DaemonSets(kc.AppsV1().DaemonSets("kube-system")).
 		WithObjectName("kube-router").
 		Until(s.Context(), func(ds *appsv1.DaemonSet) (bool, error) {
 			return true, nil
 		})
+	s.NoError(err)
```
Comment (twz123) [inline inttest/cnichange/cnichange_test.go:52]: I wonder if we wanna use Require() here and in the other places.

File: inttest/common/footloosesuite.go [hunk 3]
```diff
@@ -201,7 +200,7 @@ func (s *FootlooseSuite) SetupSuite() {
 		// Get a fresh context for the cleanup tasks.
 		ctx, cancel := signalAwareCtx(context.Background())
 		defer cancel(nil)
-		s.cleanupSuite(t, ctx)
```
Comment (twz123) [inline inttest/common/footloosesuite.go:204]: I'd prefer to keep the `t` parameter everywhere.

https://github.com/k0sproject/k0s/issues/2940#issuecomment-1490076989

File: inttest/cnichange/cnichange_test.go (hunk 2 above)
Comment (mikhail-sakhnov) [reply inttest/cnichange/cnichange_test.go:52]: I wonder if we can somehow change the embedding to use Require by default, not the Assert

Comment (juanluisvaladas) [reply inttest/cnichange/cnichange_test.go]: I used the assert one in the errors which were ignored because we weren't failing on error, but actually it makes sense to fail early so I'm changing all of these.

File: inttest/common/footloosesuite.go (hunk 3 above)
Comment (juanluisvaladas) [reply inttest/common/footloosesuite.go:204]: I didn't know the context could change, I changed the order in the parameter.

File: Makefile (hunk 1 above)
Comment (juanluisvaladas) [reply Makefile:219]: I added it to .golangci.yml and kept the variable but without defining it. This way we use .golangci.yml but we still can override the directories.

Also I split make lint into lint-copyright and lint-go, but kept the target lint. I was tired of linting copyright every time
