### PR TITLE
Re-enable Helm reconciler concurrency

### LINKED ISSUE #7305: Incorrect helm chart installation order
### What happened?

I'm not sure on which side this bug should be addressed (k0smotron or k0s). Feel free to move the bug if needed. 

When deploying `Chart` objects using the recommended way (using Chart resources instead of `spec.extensions.helm`: https://docs.k0sproject.io/stable/helm-charts/?h=chart#using-chart-custom-resources-recommended), the `order` parameter is not taken into account. 

In my case, I have two helm charts to be installed (openstack CCM and openstack CSI). The openstack CCM should be installed first, then CSI. I have the ConfigMap with `Chart` definitions and mounted it under `spec.manifests` of the K0smotronControlPlane object.

The ConfigMap `data` is as follows (`order` has been specified correctly):
```yaml
data:
  chart-openstack-cinder-csi.yaml: |
    apiVersion: helm.k0sproject.io/v1beta1
    kind: Chart
    metadata:
      name: openstack-cinder-csi
      namespace: kube-system
    spec:
      chartName: openstack-cinder-csi/openstack-cinder-csi
      version: 2.31.2
      order: 2
      releaseName: openstack-cinder-csi
      namespace: kube-system
      values: {}
  chart-openstack-cloud-controller-manager.yaml: |
    apiVersion: helm.k0sproject.io/v1beta1
    kind: Chart
    metadata:
      name: openstack-cloud-controller-manager
      namespace: kube-system
    spec:
      repository:
        url: https://kubernetes.github.io/cloud-provider-openstack/
      chartName: openstack-cloud-controller-manager/openstack-cloud-controller-manager
      version: 2.31.1
      order: 1
```

Both `Chart` objects have been created almost immediately on the cluster, but only the `openstack-cinder-csi` has been installed. The installation failed because it can't start until CCM is ready and the control plane pod (`kmc-ekaz-hcp-0`) failed after +- 10 minutes (I guess the timeout has been reached) with:
```
time="2026-03-17 16:23:48" level=error msg="Reconciler error" Chart="{openstack-cinder-csi kube-system}" component=extensions_controller controller=chart controllerGroup=helm.k0sproject.io controllerKind=Chart error="can't update or install chart: can't reconcile installation for \"openstack-cinder-csi\": an error occurred while uninstalling: uninstallation completed with 1 error(s): context deadline exceeded; original install error: context deadline exceeded" name=openstack-cinder-csi namespace=kube-system reconcileID="\"49965fde-fa0f-48c9-b1d7-4d8574fcf930\""
```

Only after that, the `cloud-controller-manager` installation started (from kmc logs):
```
time="2026-03-17 16:23:48" level=debug msg="Install or update reconciliation request: kube-system/openstack-cloud-controller-manager" component=extensions_controller extensions_type=helm
time="2026-03-17 16:23:49" level=debug msg="DaemonSet is not ready: kube-system/openstack-cloud-controller-manager. observedGeneration (0) does not match spec generation (1)." client=readychecker component=helm helm=client
time="2026-03-17 16:23:51" level=debug msg="Installed or updated reconciliation request: kube-system/openstack-cloud-controller-manager" component=extensions_controller extensions_type=helm
```

Once the ccm is installed, csi becomes ready, and the cluster becomes healthy. So, according to the `order` parameter, the CCM should have been installed first, not CSI. This incorrect order delays cluster readiness by 10+ minutes.

Workaround is to manually add the `order` prefix to the file names in the ConfigMap data, for example: 
`1-chart-openstack-cinder-csi.yaml` and `0-chart-openstack-cloud-controller-manager.yaml`.

It affects both hosted and standalone cluster deployments.

Cluster objects:
[ekaz-hcp-2-cluster.txt](https://github.com/user-attachments/files/26060797/ekaz-hcp-2-cluster.txt)
Manifest ConfigMap:
[ekaz-hcp-2-manifests-configmap.yaml](https://github.com/user-attachments/files/26060938/ekaz-hcp-2-manifests-configmap.yaml)
control plane logs:
[kmc-ekaz-hcp-0-logs.txt](https://github.com/user-attachments/files/26060798/kmc-ekaz-hcp-0-logs.txt)

### Involved Areas

Cluster API integration

### What did you expect to happen?

Helm chart order parameter is taken into account.

### Steps to reproduce

1. Deploy k0smotron v1.10.3 + CAPI openstack (in my case it's k0rdent `v1.8.0-release` branch)
2. Create the ConfigMap with openstack CCM and CSI Chart manifests specifying the correct installation order
3. Deploy openstack hosted cluster (see cluster objects manifests above as an example)
4. See that CCM does not install until the CSI helm chart installation reaches the timeout (approx. 10 minutes).

### k0smotron version

v1.10.3

### k0s version

v1.35.2+k0s.0

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by jnummelin**
## Description

We disabled Helm reconciler concurrency in #3633 since the shared Helm state did not support concurrency.

Since we've now moved to ephemeral envs for each Reconcile we can re-enable it safely.

Added a testcase that install two chart with a cross dependency, to make sure the first chart succesfully installs once the later chart brings in the dependency asynchronously. This is bit involved as we need to rely on pre-install Job checking something exists in the API. My first idea was to base the dependency to a service DNS working but turns out CoreDNS is actually borked in the addons test suite since it uses custom Docker network.

Fixes #7305

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [x] Auto test added

## Checklist

- [ ] My code follows the style [guidelines](https://docs.k0sproject.io/head/contributors/) of this project
- [ ] My commit messages are [signed-off](https://docs.k0sproject.io/head/contributors/github_workflow/)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

File: inttest/addons/addons_test.go [hunk 1]
```diff
@@ -713,6 +714,126 @@ func (as *AddonsSuite) testControllerRestartRecovery(kc *k8s.Clientset) {
...
+		Spec: helmv1beta1.ChartSpec{
+			ChartName:   as.uploadChart("order-test-chart-a"),
+			ReleaseName: chartAReleaseName,
+			Version:     "0.1.0",
+			Namespace:   metav1.NamespaceDefault,
+			Timeout:     "6m0s",
+		},
+	}
+
+	as.T().Logf("Creating Chart A (%s) first — it depends on Chart B's Service", chartAName)
```
Comment (makhov) [inline inttest/addons/addons_test.go:760]: I might be missing something, but I'm not sure using non-existent service can break helm in any circumstances. The more correct check would be installing CRD and corresponding resource in different charts.

Comment (jnummelin) [reply inttest/addons/addons_test.go:760]: This setup is 100% artificial just for testing this cross-chart dependency scenario, for sure. The CRD way is probably closer to real-life scenarios but IMO it does not really matter how this gets tested, as long as we can prove that parallelism works and charts with cross deps gets properly installed.

Comment (makhov) [reply inttest/addons/addons_test.go:760]: Yeah, sorry, I got the idea wrong. I was thinking of a scenario where installation of one of the charts might fail.

**Review by twz123 — APPROVED** [review]
