### PR TITLE
Fix airgap arm64 build

### LINKED ISSUE #1939: Airgap image bundles for arm64 not working
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.24.2+k0s.0-10-g67e8638d

### Platform

```shell
virt:~/src/k0s# lsb_release -a
-ash: lsb_release: not found
virt:~/src/k0s# uname -a
Linux virt 5.15.55-0-virt #1-Alpine SMP Tue, 19 Jul 2022 14:43:02 +0000 aarch64 Linux
virt:~/src/k0s# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.5
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

### What happened?

`make check-airgap TARGET_PLATFORM=linux/arm64` fails. Worker logs end with

> Error: failed to start worker components: can't unpack bundle bundle.tar: can't import bundle: content digest sha256:66680e1dacca60b1f95fe55e7efc197fb8f6d5514eb0667a2ada4c02ce2dd9e2: not found

### Steps to reproduce

Execute the following on an aarch64 Linux box:

1. Checkout current main branch. I tested with commit 67e8638d.
2. Run `make check-airgap TARGET_PLATFORM=linux/arm64`. This will fail with a timeout.
3. Check the airgap bundles from the release assets: `wget https://github.com/k0sproject/k0s/releases/download/v1.24.2%2Bk0s.0/k0s-airgap-bundle-v1.24.2+k0s.0-arm64`
4. Apply patch:
    ```diff

    diff --git a/inttest/Makefile b/inttest/Makefile
    index 801462ce..0864f0da 100644
    --- a/inttest/Makefile
    +++ b/inttest/Makefile
    @@ -82,8 +82,10 @@ check-ap-updater: .update-server.stamp
     .PHONY: $(smoketests)
     include Makefile.variables
    
    +K0S_IMAGES_BUNDLE ?= $(realpath ../image-bundle/bundle.tar)
    +
     $(smoketests): .footloose-alpine.stamp
    -       K0S_IMAGES_BUNDLE="$(realpath ../image-bundle/bundle.tar)" K0S_PATH="$(realpath ../k0s)" go test -count=1 -v -timeout $(TIMEOUT) github.com/k0sproject/k0s/inttest/$(subst check-,,$@)
    +       K0S_IMAGES_BUNDLE="$(K0S_IMAGES_BUNDLE)" K0S_PATH="$(realpath ../k0s)" go test -count=1 -v -timeout $(TIMEOUT) github.com/k0sproject/k0s/inttest/$(subst check-,,$@)
    
     .PHONY: clean
     clean:
    ```
5. Run `make check-airgap K0S_IMAGES_BUNDLE=$(pwd)/k0s-airgap-bundle-v1.24.2+k0s.0-arm64 TARGET_PLATFORM=linux/arm64`. This timeouts, too.

### Expected behavior

The integration test also works on arm64, i.e. the produced image bundles work.

### Actual behavior

The integration test times out. The logs of the workers 

### Screenshots and logs

_No response_

### Additional context

The arm image bundle might also be non-fuctional, but I didn't check. Would be also nice if the image bundle generation detects the required target platform, instead of just assuming amd64.

### PR DESCRIPTION
**Pull request by makhov**
Signed-off-by: Alexey Makhov <amakhov@mirantis.com>

## Description

Fixes #1939

For airgap bundles, we export images for the platform into the tar archive and then try to import them on k0s startup. 
The problem here is that by default during import containerd matches platforms not strictly, so for arm64 it tries to import both arm64 and armv7 images, but there are no armv7 blobs in the archive.

So, the actual fix is to change the `Only` matcher to the `OnlyStrict` one.

There is the PR with a similar fix for `ctr import` command: https://github.com/containerd/containerd/pull/6906

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [x] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pkg/component/worker/ocibundle.go [hunk 1]
```diff
@@ -61,7 +62,7 @@ func (a *OCIBundleReconciler) Run(ctx context.Context) error {
 	var client *containerd.Client
 	sock := filepath.Join(a.k0sVars.RunDir, "containerd.sock")
 	err = retry.Do(func() error {
-		client, err = containerd.New(sock, containerd.WithDefaultNamespace("k8s.io"))
+		client, err = containerd.New(sock, containerd.WithDefaultNamespace("k8s.io"), containerd.WithDefaultPlatform(platforms.OnlyStrict(platforms.DefaultSpec())))
```
Comment (twz123) [inline pkg/component/worker/ocibundle.go:65]: Oh yeah!

**Review by twz123 — APPROVED** [review]
