### PR TITLE
check if env var ETCD_UNSUPPORTED_ARCH has been set for ARM processors

### LINKED ISSUE #424: Error "ETCD_UNSUPPORTED_ARCH=arm64"
**Version**
```
v0.7.0
```
**Platform**
Which platform did you run k0s on?
```
Raspberry Pi 4B 4GB with Ubuntu 20.10 arm64 Image

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```
**What happened?**
```
INFO[2020-11-18 19:13:25] Starting to supervise                         component=etcd
INFO[2020-11-18 19:13:25] Started succesfully, go nuts                  component=etcd
INFO[2020-11-18 19:13:25] etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set  component=etcd
WARN[2020-11-18 19:13:25] exit status 1                                 component=etcd
INFO[2020-11-18 19:13:25] respawning in 5 secs                          component=etcd
INFO[2020-11-18 19:13:30] Started succesfully, go nuts                  component=etcd
INFO[2020-11-18 19:13:30] etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set  component=etcd
WARN[2020-11-18 19:13:30] exit status 1                                 component=etcd
INFO[2020-11-18 19:13:30] respawning in 5 secs                          component=etcd
INFO[2020-11-18 19:13:35] Started succesfully, go nuts                  component=etcd
INFO[2020-11-18 19:13:35] etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=arm64 set  component=etcd
WARN[2020-11-18 19:13:35] exit status 1                                 component=etcd
INFO[2020-11-18 19:13:35] respawning in 5 secs                          component=etcd
```

**How To Reproduce**
`k0s server --enable-worker` on arm64

**Additional context**
I just found this: https://github.com/etcd-io/etcd/issues/10677

### PR DESCRIPTION
**Pull request by jasmingacic**
Fixes #424 
The PR will check if requested environment variable is set. If not it will print an error message in k0s logs.

@kke I ran on to this issue when running k0sctl against an ARM box. Should this be enough for k0sctl to detect what is required?

### CODE REVIEW

File: pkg/component/controller/etcd.go [hunk 1]
```diff
@@ -245,3 +252,12 @@ func (e *Etcd) Healthy() error {
 	cancel()
 	return err
 }
+
+func detectUnsupportedEtcdArch() error {
+	if strings.Contains(runtime.GOARCH, "arm") {
+		if _, set := os.LookupEnv("ETCD_UNSUPPORTED_ARCH"); !set {
```
Comment (jnummelin) [inline pkg/component/controller/etcd.go:258]:
```suggestion
		if os.Getenv("ETCD_UNSUPPORTED_ARCH") != runtime.ARCH {
```
The current way makes the check pass in e.g. `arm64` archi bu setting up env `ETCD_UNSUPPORTED_ARCH=foo`. And that'll trip over etcd again.

**Review by jnummelin — CHANGES_REQUESTED** [review]

**Review by jnummelin — APPROVED** [review]

**Comment by ypnos** [comment]
Now when I start K0s I get the error as expected.
However when I set the environment variable, I find this in the logs:

> time="2022-03-28 13:24:49" level=info msg="{\"level\":\"warn\",\"ts\":1648466689.203589,\"caller\":\"flags/flag.go:93\",\"msg\":\"unrecognized environment variable\",\"environment-variable\":\"ETCD_UNSUPPORTED_ARCH=arm64\"}" component=etcd

In etcd documentation, ARM64 is now also listed as supported: https://etcd.io/docs/v3.5/op-guide/supported-platform/

So I wonder if this is still necessary or should be reverted?

**Comment by twz123** [comment]
See #1624
