### PR TITLE
fetch node object from apiserver when (un)cordoning

### LINKED ISSUE #3739: Autopilot "failed to covert signalNode to Node"
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

### Version

v1.28.3+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "f3dd8b42fb36934801018766083b245a390c1c8e64af79b44311ef2a534bb765" (from machine) (pass)
Total memory: 3.8 GiB (pass)
Disk space available for /var/lib/k0s: 102.7 GiB (pass)
Name resolution: localhost: [127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.15.0-88-generic (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

When applying an autopilot plan to a single node controller installed with `k0s install controller --enable-worker`, the plan is stuck in `ScheduleableWait` indefinitely while the logs imply there was an error while casting some internal types. 

### Steps to reproduce

1. install one minor k0s 1.28.3 with `k0s install controller --enable-worker`
2. try to upgrade to 1.28.4 with autopilot:
```
apiVersion: autopilot.k0sproject.io/v1beta2
kind: Plan
metadata:
  name: autopilot
spec:
  id: id1234
  timestamp: now
  commands:
    - k0supdate:
        version: v1.28.4+k0s.0
        platforms:
          linux-amd64:
            url: https://get.k0sproject.io/v1.28.4%2Bk0s.0/k0s-v1.28.4+k0s.0-amd64
        targets:
          controllers:
            discovery:
              static:
                nodes:
                  - k0s1
```

4. check `journalcl -u k0scontroller.service`

### Expected behavior

autopilot should be able to upgrade the node

### Actual behavior

autopilot fails to upgrade the node

### Screenshots and logs

```
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=info msg="starting to cordon node k0s1" component=autopilot controller=ControlNode leadermode=true object=ControlNode reconciler=cordoning signalnode=k0s1
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=error msg="Reconciler error" ControlNode="{\"name\":\"k0s1\"}" component=controller-runtime controller=controlnode controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to covert signalNode to Node" name=k0s1 namespace= reconcileID="\"ba982757-a226-4b56-9ce4-0c06346b53f1\""
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=info msg="starting to cordon node k0s1" component=autopilot controller=ControlNode leadermode=true object=ControlNode reconciler=cordoning signalnode=k0s1
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=error msg="Reconciler error" ControlNode="{\"name\":\"k0s1\"}" component=controller-runtime controller=controlnode controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to covert signalNode to Node" name=k0s1 namespace= reconcileID="\"cec63666-7850-4d47-95c9-bfb75f6607c2\""
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=info msg="starting to cordon node k0s1" component=autopilot controller=ControlNode leadermode=true object=ControlNode reconciler=cordoning signalnode=k0s1
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=error msg="Reconciler error" ControlNode="{\"name\":\"k0s1\"}" component=controller-runtime controller=controlnode controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to covert signalNode to Node" name=k0s1 namespace= reconcileID="\"7dc8cb6f-63fa-4842-b9bf-e661c8091b99\""
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=info msg="starting to cordon node k0s1" component=autopilot controller=ControlNode leadermode=true object=ControlNode reconciler=cordoning signalnode=k0s1
Nov 21 15:22:01 k0s1 k0s[1119]: time="2023-11-21 15:22:01" level=error msg="Reconciler error" ControlNode="{\"name\":\"k0s1\"}" component=controller-runtime controller=controlnode controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to covert signalNode to Node" name=k0s1 namespace= reconcileID="\"14eeb88d-a039-4bac-a34d-7a229df19782\""
Nov 21 15:22:02 k0s1 k0s[1119]: time="2023-11-21 15:22:02" level=info msg="starting to cordon node k0s1" component=autopilot controller=ControlNode leadermode=true object=ControlNode reconciler=cordoning signalnode=k0s1
Nov 21 15:22:02 k0s1 k0s[1119]: time="2023-11-21 15:22:02" level=error msg="Reconciler error" ControlNode="{\"name\":\"k0s1\"}" component=controller-runtime controller=controlnode controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to covert signalNode to Node" name=k0s1 namespace= reconcileID="\"31810aa0-d88e-449c-a0e0-9cc1fd1051ee\""
Nov 21 15:22:03 k0s1 k0s[1119]: time="2023-11-21 15:22:03" level=info msg="starting to cordon node k0s1" component=autopilot controller=ControlNode leadermode=true object=ControlNode reconciler=cordoning signalnode=k0s1
Nov 21 15:22:03 k0s1 k0s[1119]: time="2023-11-21 15:22:03" level=error msg="Reconciler error" ControlNode="{\"name\":\"k0s1\"}" component=controller-runtime controller=controlnode controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to covert signalNode to Node" name=k0s1 namespace= reconcileID="\"49e8cdd3-8241-4ad1-9f05-23e34ff61778\""
Nov 21 15:22:05 k0s1 k0s[1119]: time="2023-11-21 15:22:05" level=info msg=Processing command=k0supdate component=autopilot controller=plans leadermode=true state=schedulablewait
Nov 21 15:22:05 k0s1 k0s[1119]: time="2023-11-21 15:22:05" level=info msg="Reconciling controller/worker signal node statuses" command=k0supdate component=autopilot controller=plans leadermode=true state=schedulablewait
Nov 21 15:22:05 k0s1 k0s[1119]: time="2023-11-21 15:22:05" level=info msg="Signal node 'k0s1' status changed from 'SignalSent' to 'SignalSent' (reason: Cordoning)" command=k0supdate component=autopilot controller=plans leadermode=true
Nov 21 15:22:05 k0s1 k0s[1119]: time="2023-11-21 15:22:05" level=info msg="No applicable transitions available, requesting retry" command=k0supdate component=autopilot controller=plans leadermode=true state=schedulablewait
Nov 21 15:22:05 k0s1 k0s[1119]: time="2023-11-21 15:22:05" level=info msg="Requeuing request due to explicit retry" component=autopilot controller=plans leadermode=true
Nov 21 15:22:06 k0s1 k0s[1119]: time="2023-11-21 15:22:06" level=info msg="starting to cordon node k0s1" component=autopilot controller=ControlNode leadermode=true object=ControlNode reconciler=cordoning signalnode=k0s1
Nov 21 15:22:06 k0s1 k0s[1119]: time="2023-11-21 15:22:06" level=error msg="Reconciler error" ControlNode="{\"name\":\"k0s1\"}" component=controller-runtime controller=controlnode controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to covert signalNode to Node" name=k0s1 namespace= reconcileID="\"ddf7b121-5bc3-4dc1-bb93-e92246692f92\""
```

### Additional context

`kubectl get node k0s1 -o yaml`:

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2023-11-21T15:18:07Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: k0s1
    kubernetes.io/os: linux
    node.k0sproject.io/role: control-plane
  name: k0s1
  resourceVersion: "474"
  uid: 3a29d53c-f316-4627-8d95-e22c34f3b7ac
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
status:
  addresses:
  - address: 192.168.122.86
    type: InternalIP
  - address: k0s1
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: "113601576772"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 3902992Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 123265600Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 4005392Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2023-11-21T15:18:19Z"
    lastTransitionTime: "2023-11-21T15:18:07Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2023-11-21T15:18:19Z"
    lastTransitionTime: "2023-11-21T15:18:07Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2023-11-21T15:18:19Z"
    lastTransitionTime: "2023-11-21T15:18:07Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2023-11-21T15:18:19Z"
    lastTransitionTime: "2023-11-21T15:18:19Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  nodeInfo:
    architecture: amd64
    bootID: e69c52fd-803c-4480-8f72-1ff494c03855
    containerRuntimeVersion: containerd://1.7.8
    kernelVersion: 5.15.0-88-generic
    kubeProxyVersion: v1.28.3+k0s
    kubeletVersion: v1.28.3+k0s
    machineID: 9b4148c7aacd41d69380771367c2628d
    operatingSystem: linux
    osImage: Ubuntu 22.04.3 LTS
    systemUUID: 9b4148c7-aacd-41d6-9380-771367c2628d
```

### PR DESCRIPTION
**Pull request by danj-replicated**
## Description

when cordoning/uncordoning controlNodes for autopilot, fetch Node object from APIserver instead of trying to cast from signalNode.

Fixes #3739

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pkg/autopilot/controller/signal/k0s/cordon.go [hunk 1]
```diff
@@ -147,9 +147,11 @@ func (r *cordoning) moveToNextState(ctx context.Context, signalNode crcli.Object
 // draining ignores daemonsets
 func (r *cordoning) drainNode(ctx context.Context, signalNode crcli.Object) error {
 	logger := r.log.WithField("signalnode", signalNode.GetName()).WithField("phase", "drain")
-	node, ok := signalNode.(*corev1.Node)
-	if !ok {
-		return fmt.Errorf("failed to covert signalNode to Node")
+
+	//get node from client
+	node := &corev1.Node{}
+	if err := r.client.Get(ctx, crcli.ObjectKey{Name: signalNode.GetName()}, node); err != nil {
```
Comment (twz123) [inline pkg/autopilot/controller/signal/k0s/cordon.go:153]: I think the Node lookup is only necessary when the object is not already a Node. So maybe shove this into the else branch?

Comment (danj-replicated) [reply pkg/autopilot/controller/signal/k0s/cordon.go]: I think I understood what you meant. there wasn't an existing else branch in that codepath though

**Review by twz123 — APPROVED** [review]
Thanks a lot for poking into this!
