### PR TITLE
fix: controller worker upgrades fail with load balancer

### LINKED ISSUE #6071: Kubelet race condition during startup: "services have not yet been read at least once, cannot construct envvars"
### Before creating an issue, make sure you've checked the following:

- [ ] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.8.0-1031-gcp #33~22.04.1-Ubuntu SMP Fri May 23 19:49:56 UTC 2025 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Version

v1.31.8+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 31.3 GiB (pass)
File system of /var/lib: ext4 (pass)
Disk space available for /var/lib/k0s: 84.8 GiB (pass)
Relative disk space available for /var/lib/k0s: 87% (pass)
Name resolution: localhost: [127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.8.0-1031-gcp (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in PATH: modprobe: /usr/sbin/modprobe (pass)
  Executable in PATH: mount: /usr/bin/mount (pass)
  Executable in PATH: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: built-in (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: built-in (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: built-in (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

Multiple pods fail to start with `CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars` during k0s startup or after system restarts. This affects containers that reference Kubernetes Services in their environment variables or use EnvFrom with service references.

### Steps to reproduce

1. Set up a 3-node HA k0s cluster with Node Local Load Balancing (NLLB) enabled
2. Deploy applications with pods that reference services in environment variables (especially using EnvFrom or service discovery)
3. Perform a k0s autopilot upgrade from k0s v1.30.9+k0s.0 to v1.31.8+k0s.0 across the multinode cluster
4. During the upgrade process, observe pods failing to start with the envvars error

**Note**: This issue does not happen consistently but is frequently observed during multinode upgrades in HA clusters with NLLB enabled.

### Expected behavior

Kubelet should wait for service informer cache to sync before attempting to start containers that depend on service information for environment variable construction.

### Actual behavior

Pods fail repeatedly with `CreateContainerConfigError` until service cache eventually syncs, causing application downtime and failed deployments.

### Screenshots and logs

Full logs:  [k0scontroller-logs.txt](https://github.com/user-attachments/files/21004558/k0scontroller-logs.txt)

**Relevant logs**

  Jun 30 23:19:31 diamon-ec-3 k0s[32219]: time="2025-06-30 23:19:31" level=info msg="E0630 23:19:31.129668   32369 kuberuntime_manager.go:1274] \"Unhandled Error\" err=\"init container &Container{Name:bootstrap-controller,...} start failed in pod 
  mlflow-postgres-1_kotsadm(56211f99-e759-412c-98ca-e0ef872afd9c): CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars\"" component=kubelet stream=stderr

  Jun 30 23:19:31 diamon-ec-3 k0s[32219]: time="2025-06-30 23:19:31" level=info msg="E0630 23:19:31.424076   32369 kuberuntime_manager.go:1274] \"Unhandled Error\" err=\"container &Container{Name:calico-node,...} start failed in pod 
  calico-node-mcb4d_kube-system(f3037382-bf45-41c1-a1c9-10a5e3590669): CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars\"" component=kubelet stream=stderr

  Jun 30 23:19:31 diamon-ec-3 k0s[32219]: time="2025-06-30 23:19:31" level=info msg="E0630 23:19:31.426884   32369 kuberuntime_manager.go:1274] \"Unhandled Error\" err=\"container &Container{Name:node-agent,...} start failed in pod node-agent-m2d4j_velero(04b3885f-452e-449d-b36c-d4affc4b8ed8):
   CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars\"" component=kubelet stream=stderr

  Jun 30 23:19:31 diamon-ec-3 k0s[32219]: time="2025-06-30 23:19:31" level=info msg="E0630 23:19:31.432289   32369 kuberuntime_manager.go:1274] \"Unhandled Error\" err=\"container &Container{Name:kube-proxy,...} start failed in pod 
  kube-proxy-g5k7h_kube-system(270ac2d8-d502-4fcd-9537-edef4c10ce7f): CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars\"" component=kubelet stream=stderr

  Service reflector connection failures (showing the race condition):
  Jun 30 21:07:35 diamon-ec-3 k0s[6312]: time="2025-06-30 21:07:35" level=info msg="W0630 21:07:35.833038    6435 reflector.go:539] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: failed to list *v1.Service: Get \"https://127.0.0.1:7443/api/v1/services?limit=500&resourceVersion=0\": dial
   tcp 127.0.0.1:7443: connect: connection refused" component=kubelet stream=stderr

  Jun 30 21:07:35 diamon-ec-3 k0s[6312]: time="2025-06-30 21:07:35" level=info msg="E0630 21:07:35.833123    6435 reflector.go:147] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:229: Failed to watch *v1.Service: failed to list *v1.Service: Get 
  \"https://127.0.0.1:7443/api/v1/services?limit=500&resourceVersion=0\": dial tcp 127.0.0.1:7443: connect: connection refused" component=kubelet stream=stderr

**Analysis**

Startup timing showing the race condition:
- 21:07:26 - API server starts: time="2025-06-30 21:07:26" level=info msg="starting APIServer"
- 21:07:29 - Kubelet starts: time="2025-06-30 21:07:29" level=info msg="starting Kubelet"
- 21:07:35 - Service reflector fails to connect (8 seconds after kubelet start)
- 23:19:31 - Multiple pods fail with envvars error after restart

### Additional context

**Nodes**:
```bash
kubectl get nodes -owide
NAME          STATUS                     ROLES           AGE   VERSION       INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
diamon-ec-1   Ready                      control-plane   18h   v1.30.9+k0s   10.150.0.21     <none>        Ubuntu 22.04.5 LTS   6.8.0-1031-gcp   containerd://1.7.24
diamon-ec-2   Ready,SchedulingDisabled   control-plane   18h   v1.30.9+k0s   10.150.15.221   <none>        Ubuntu 22.04.5 LTS   6.8.0-1031-gcp   containerd://1.7.24
diamon-ec-3   Ready                      control-plane   18h   v1.31.8+k0s   10.150.15.232   <none>        Ubuntu 22.04.5 LTS   6.8.0-1031-gcp   containerd://1.7.27
```

### PR DESCRIPTION
**Pull request by emosbaugh**
## Description

Fixes #6071 

When a multi-controller controller+worker cluster with a load balancer is upgraded, the kubelet on the controller+worker that is upgraded first can get directed to any of the other controller upstreams. This violates the Kubernetes [version skew policy](https://kubernetes.io/releases/version-skew-policy/#kubelet) connecting to an upstream running the prior version. Upgrades from 1.30 to 1.31 fail due to a change in the API schema.

```
Jun 30 23:19:28 diamon-ec-3 k0s[32219]: time="2025-06-30 23:19:28" level=info msg="E0630 23:19:28.670043   32369 reflector.go:158] \"Unhandled Error\" err=\"k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: \\\"spec.clusterIP\\\" is not a known field selector: only \\\"metadata.name\\\", \\\"metadata.namespace\\\"\" logger=\"UnhandledError\"" component=kubelet stream=stderr
```

This change overrides the API server address in the Kubelet conf to connect directly to the API server running on localhost rather than through the load balancer.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist

- [x] My code follows the style [guidelines](https://docs.k0sproject.io/head/contributors/) of this project
- [x] My commit messages are [signed-off](https://docs.k0sproject.io/head/contributors/github_workflow/)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by emosbaugh** [comment]
Autopilot upgrades are no longer working in my manual testing. I am currently trying to track the issue down.

**Comment by emosbaugh** [comment]
> Autopilot upgrades are no longer working in my manual testing. I am currently trying to track the issue down.

This was an issue with the version i used when building. It didnt match the autopilot plan version so it was stuck.

**Comment by emosbaugh** [comment]
Is it possible to backport this change? Thank you!

**Comment by emosbaugh** [comment]
@jnummelin @twz123 can i get a review here? thanks!

File: pkg/component/worker/utils.go [hunk 1]
```diff
@@ -139,3 +143,108 @@ func writeKubeletBootstrapKubeconfig(kubeconfig clientcmdapi.Config) (string, er
...
+
+	// Determine the local API server address
+	var localAPIServer string
+	if apiSpec.OnlyBindToAddress {
+		// API server binds only to specific address, use that address with proper IPv6 bracketing
+		localAPIServer = net.JoinHostPort(apiSpec.Address, strconv.Itoa(apiSpec.Port))
+	} else {
+		// API server binds to all interfaces, use localhost
+		// Try to resolve localhost to get the appropriate loopback address (IPv4/IPv6)
+		loopbackIP, err := getLoopbackIP(ctx)
```
Comment (juanluisvaladas) [inline pkg/component/worker/utils.go:168]: Most places in our codebase just use localhost, probably could be simpler but I don't think this could cause any harm.

Comment (emosbaugh) [reply pkg/component/worker/utils.go:168]: I assume you are suggesting removing most of this block of code and changing line 173 to the following:

```
localAPIServer = net.JoinHostPort("localhost", strconv.Itoa(apiSpec.Port))
```

I see that the IP address is likely not necessary as this is not a bind address. Would you like me to make that change ahead of merging?

Comment (juanluisvaladas) [reply pkg/component/worker/utils.go:168]: Nah, no need, go ahead and merge it.

Comment (emosbaugh) [reply pkg/component/worker/utils.go:168]: This is difficult to test but for some reason when i use localhost I get the following error when trying to get logs or exec

```
$ sudo k0s kubectl logs -n kube-system   fluentd-elasticsearch-lzb48
Error from server: Get "https://10.138.0.40:10250/containerLogs/kube-system/fluentd-elasticsearch-lzb48/fluentd-elasticsearch": No agent available
```

not a whole lot that makes sense in the controller+worker logs

```
Sep 05 19:18:54 ethanm-ec-2.c.replicated-qa.internal k0s[14446]: time="2025-09-05 19:18:54" level=info msg="\tError updating APIService \"v1beta1.metrics.k8s.io\" with err: failed to download v1beta1.metrics.k8s.io: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: service unavailable" component=kube-apiserver stream=stderr
Sep 05 19:18:54 ethanm-ec-2.c.replicated-qa.internal k0s[14446]: time="2025-09-05 19:18:54" level=info msg="\t, Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]" component=kube-apiserver stream=stderr
Sep 05 19:18:54 ethanm-ec-2.c.replicated-qa.internal k0s[14446]: time="2025-09-05 19:18:54" level=info msg=" > logger=\"UnhandledError\"" component=kube-apiserver stream=stderr
Sep 05 19:18:54 ethanm-ec-2.c.replicated-qa.internal k0s[14446]: time="2025-09-05 19:18:54" level=info msg="W0905 19:18:54.337405   14483 handler_proxy.go:99] no RequestInfo found in the context" component=kube-apiserver stream=stderr
Sep 05 19:18:54 ethanm-ec-2.c.replicated-qa.internal k0s[14446]: time="2025-09-05 19:18:54" level=info msg="E0905 19:18:54.337470   14483 controller.go:146] \"Unhandled Error\" err=<" component=kube-apiserver stream=stderr
```
