### PR TITLE
Start konnectivity BEFORE api-server

### LINKED ISSUE #3586: Unable to update to v1.28.2+k0s.0 from v1.27.5+k0s.0
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Version

v1.28.2+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Machine ID: "c80592dd1800ac57dcc209e4e8b0da89b937e4d0d4ba3dfa2a7e25b1085d344a" (from machine) (pass)
Total memory: 5.8 GiB (pass)
Disk space available for /var/lib/k0s: 12.3 GiB (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.1.0-13-amd64 (pass)
  Max. file descriptors per process: current: 1048576 / max: 1048576 (pass)
  AppArmor: active (pass)
  Executable in path: umount: /usr/bin/umount (pass)
  Executable in path: umount: /usr/bin/umount (pass)
  Executable in path: umount: /usr/bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

I have a k0s cluster with 3 control nodes and 5 worker nodes created with k0sctl.
While trying to upgrade to the 1.28 version the `k0scontroller.service` won't start properly and keeps restarting.

### Steps to reproduce

1. Have a k0s cluster initialised with k0sctl for v1.27.5+k0s.0
2. Run k0sctl apply with v1.28.2+k0s.0 version

### Expected behavior

The k0s cluster upgrades to the new version

### Actual behavior

The upgrade fails and the node becomes unhealthy

### Screenshots and logs

Service logs:
[k0s-fail.txt](https://github.com/k0sproject/k0s/files/12904569/k0s-fail.txt)

From the logs it seems that the konnectivity-server is not running
```
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="W1014 10:19:54.887210  147080 logging.go:59] [core] [Channel #597 SubChannel #599] grpc: addrConn.createTransport failed to connect to {" component=kube-apiserver stream=stderr
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="  \"Addr\": \"/run/k0s/konnectivity-server/konnectivity-server.sock\"," component=kube-apiserver stream=stderr
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="  \"ServerName\": \"/run/k0s/konnectivity-server/konnectivity-server.sock\"," component=kube-apiserver stream=stderr
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="  \"Attributes\": null," component=kube-apiserver stream=stderr
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="  \"BalancerAttributes\": null," component=kube-apiserver stream=stderr
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="  \"Type\": 0," component=kube-apiserver stream=stderr
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="  \"Metadata\": null" component=kube-apiserver stream=stderr
Oct 14 10:19:54 k3s-master-1 k0s[147056]: time="2023-10-14 10:19:54" level=info msg="}. Err: connection error: desc = \"transport: Error while dialing: dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: connect: no such file or directory\"" component=kube-apiserver stream=stderr
```

k0sctl.yaml
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    # Master nodes
    - ssh:
        address: 192.168.2.21
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: controller+worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-1"

    - ssh:
        address: 192.168.2.22
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: controller+worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-2"

    - ssh:
        address: 192.168.2.23
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: controller+worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-3"

    # Worker nodes
    - ssh:
        address: 192.168.2.31
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-1"
    - ssh:
        address: 192.168.2.32
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-1"

    - ssh:
        address: 192.168.2.33
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-2"
    - ssh:
        address: 192.168.2.34
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-2"

    - ssh:
        address: 192.168.2.35
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-3"
    - ssh:
        address: 192.168.2.36
        user: k8s
        keyPath: ~/.ssh/id_ed25519
      role: worker
      installFlags:
        - --labels="topology.kubernetes.io/zone=home-3"

  k0s:
    # renovate: datasource=github-releases depName=k0sproject/k0s
    version: "v1.28.2+k0s.0"
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: 192.168.2.20
          sans:
            - 192.168.2.20
            - 192.168.2.21
            - 192.168.2.22
            - 192.168.2.23

        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12

          provider: custom
          kubeProxy:
            disabled: true

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jnummelin**
## Description

In kube 1.28, api-server is more stringent in checking the konnectivity socket reachability. So upgrading from 1.28 make the startup quite slow. Eventually api-server does get ready and thus allows k0s to start konnectivity.

To mitigate this, this PR changes the order to start konnectivity first.

This requires to break down the components a bit, into three different components:
* `Konnectivity`: konnectivity-server logic
* `KonnectivityAgent`: Only responsible for managing the konnectivity-agent deployment into workers
* `K0sControllersLeaseCounter`: Enhanced now to support pub-sub like functionality to subscribe to controll count events. `

Fixes #3586 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [x] Auto test added

## Checklist:

- [ ] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [ ] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pkg/component/controller/controllersleasecounter.go [hunk 1]
```diff
@@ -102,3 +110,52 @@ func (l *K0sControllersLeaseCounter) Stop() error {
...
+
+// Notify the subscribers about the current controller count
+func (l *K0sControllersLeaseCounter) notifySubscribers(count int) {
+	logrus.WithFields(logrus.Fields{"component": "controllerlease"}).Debugf("notifying subscribers (%d) about controller count: %d", len(l.subscribers), count)
+	for _, ch := range l.subscribers {
+		// Use non-blocking send to avoid blocking the loop
+		select {
+		case ch <- count:
+		default:
+		}
```
Comment (kke) [inline pkg/component/controller/controllersleasecounter.go:153]: I'm not sure if this is a problem, but this will cause the subscribers to not get the update if they are not receiving messages from the channel at that exact moment or if the channel is full for example because it's still processing the previous update.

Maybe a timeout, something like:

```suggestion
		select {
		case ch <- count:
		case <-time.After(time.Second):
		}
```

File: pkg/component/controller/konnectivity.go [hunk 2]
```diff
@@ -22,53 +22,49 @@ import (
...
 	"github.com/k0sproject/k0s/internal/pkg/sysinfo/machineid"
-	"github.com/k0sproject/k0s/internal/pkg/templatewriter"
 	"github.com/k0sproject/k0s/internal/pkg/users"
 	"github.com/k0sproject/k0s/pkg/apis/k0s/v1beta1"
 	"github.com/k0sproject/k0s/pkg/assets"
 	"github.com/k0sproject/k0s/pkg/component/manager"
 	"github.com/k0sproject/k0s/pkg/component/prober"
 	"github.com/k0sproject/k0s/pkg/config"
 	"github.com/k0sproject/k0s/pkg/constant"
+	k0scontext "github.com/k0sproject/k0s/pkg/context"
```
Comment (kke) [inline pkg/component/controller/konnectivity.go:38]: I made a PR to rename the package: https://github.com/k0sproject/k0s/pull/3640

File: pkg/component/controller/konnectivity.go [hunk 3]
```diff
@@ -164,49 +156,53 @@ func (k *Konnectivity) runServer(ctx context.Context) {
...
+func (k *Konnectivity) runServer(ctx context.Context, count int) error {
+	args := k.defaultArgs()
+	args["--server-count"] = strconv.Itoa(count)
+
+	// Stop supervisor
+	if k.supervisor != nil {
+		k.EmitWithPayload("restarting konnectivity server due to server count change",
+			map[string]interface{}{"serverCount": count})
+		if err := k.supervisor.Stop(); err != nil {
+			logrus.Errorf("failed to stop supervisor: %s", err)
```
Comment (kke) [inline pkg/component/controller/konnectivity.go:180]: Maybe use a logger with the `component` field

File: pkg/component/controller/konnectivity.go [hunk 4]
```diff
@@ -164,49 +156,53 @@ func (k *Konnectivity) runServer(ctx context.Context) {
...
+		BinPath: assets.BinPath("konnectivity-server", k.K0sVars.BinDir),
+		DataDir: k.K0sVars.DataDir,
+		RunDir:  k.K0sVars.RunDir,
+		Args:    args.ToArgs(),
+		UID:     k.uid,
+	}
+	err := k.supervisor.Supervise()
+	if err != nil {
+		k.EmitWithPayload("failed to run konnectivity server", err)
+		logrus.Errorf("failed to start konnectivity supervisor: %s", err)
```
Comment (kke) [inline pkg/component/controller/konnectivity.go:196]: Maybe use a logger with the `component` field

Comment (kke) [reply pkg/component/controller/konnectivity.go:196]: `k.log` should work I think.

File: pkg/component/controller/konnectivityagent.go [hunk 5]
```diff
@@ -0,0 +1,301 @@
...
+				} else {
+					cfg.ProxyServerPort = uint16(*v1beta1.DefaultEnvoyProxy().KonnectivityServerBindPort)
+				}
+			default:
+				return fmt.Errorf("unsupported node-local load balancer type: %q", k.clusterConfig.Spec.Network.NodeLocalLoadBalancing.Type)
+			}
+		}
+	}
+
+	if cfg == k.previousConfig {
```
Comment (kke) [inline pkg/component/controller/konnectivityagent.go:165]: This only works when `cfg` or `k.previousConfig` is nil. I'm not sure why the compiler doesn't catch this as it will crash when that is not the case.

```suggestion
	if cfg.Equals(k.previousConfig) {
```

Similar looking mistake seems to exist in several components 🤔

Comment (kke) [reply pkg/component/controller/konnectivityagent.go:165]: The compiler should catch it 🤔 https://go.dev/play/p/D_lg51bSbZH

Comment (kke) [reply pkg/component/controller/konnectivityagent.go:165]: Ah it isn't stringmap, got confused somehow.

Structs should be comparable if they only include Comparable fields.

**Review by kke — APPROVED** [review]
