### PR TITLE
Detect --hostname-override flag in Autopilot for controller+worker nodes

### LINKED ISSUE #4857: Autopilot can't update controller+worker with --kubelet-extra-args="--hostname-override"
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
any
```

### Version

any

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

When k0s is running in controller+worker mode, the autopilot update tries to cordon Kubernetes node using the name of the ControlNode object. 
It won't work if the --kubelet-extra-args="--hostname-override" flag or the AUTOPILOT_HOSTNAME environment variable is set and they don't match each other. 

k0smotron issue, caused by the bug: https://github.com/k0sproject/k0smotron/issues/670

### Steps to reproduce

1. Run k0s with controller+worker
2. Apply autopilot plan for controllers

### Expected behavior

The node is updated

### Actual behavior

The Plan gets stuck with the error:
```
Aug 09 16:41:14 ip-10-0-81-251.us-west-1.compute.internal k0s[4170]: time="2024-08-09 16:41:14" level=error msg="Reconciler error" ControlNode="{aws-cl-1-cp-1 }" component=controller-runtime controller=controlno
de controllerGroup=autopilot.k0sproject.io controllerKind=ControlNode error="failed to get node: Node \"aws-cl-1-cp-1\" not found" name=aws-cl-1-cp-1 namespace= reconcileID="\"b20149ec-44b0-4b69-b45a-f71ec1f056f5\""
```

### Screenshots and logs

_No response_

### Additional context

Also, `kubernetes.io/hostname` and `status.address[type=Hostname]` probably should use the node name. 
```
apiVersion: autopilot.k0sproject.io/v1beta2
kind: ControlNode
metadata:
  annotations:
    autopilot.k0sproject.io/mode: controller+worker
  creationTimestamp: "2024-08-12T17:13:06Z"
  generation: 1
  labels:
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: aws-cl-1-cp-0
    kubernetes.io/os: linux
  name: aws-cl-1-cp-0
  resourceVersion: "470"
  uid: 1c3b5b23-2fd6-4a41-b935-e05bf013cba5
status:
  addresses:
  - address: 10.0.67.254
    type: InternalIP
  - address: aws-cl-1-cp-0
    type: Hostname
```

The issue can be addressed by detecting and using `--hostname-override` and real hostname in `kubernetes.io/hostname`/ `status.addresses` and then using those fields in node cordoning.

### PR DESCRIPTION
**Pull request by makhov**
## Description

Fixes #4857 

Detect kubernetes node name from `--hostname-override` flag in Autopilot for controller+worker nodes. 
Currently, if `--hostname-override` flag is used, Autopilot can't cordon the worker node, because names don't match.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [ ] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pkg/autopilot/controller/setup.go [hunk 1]
```diff
@@ -42,21 +42,23 @@ type SetupController interface {
...
+	k0sDataDir       string
+	enableWorker     bool
+	kubeletExtraArgs string
 }
 
 var _ SetupController = (*setupController)(nil)
 
 // NewSetupController creates a `SetupController`
-func NewSetupController(logger *logrus.Entry, cf apcli.FactoryInterface, k0sDataDir string, enableWorker bool) SetupController {
+func NewSetupController(logger *logrus.Entry, cf apcli.FactoryInterface, k0sDataDir, kubeletExtraArgs string, enableWorker bool) SetupController {
```
Comment (twz123) [inline pkg/autopilot/controller/setup.go:55]: We could store the kubelet's node name directly in the setup controller, instead of the whole extra args, and do the args parsing in the root controller instead.

File: pkg/autopilot/controller/setup.go [hunk 2]
```diff
@@ -140,7 +147,7 @@ func (sc *setupController) createControlNode(ctx context.Context, cf apcli.Facto
 				Name: name,
 				// Create the usual os and arch labels as this describes a controller node
 				Labels: map[string]string{
-					corev1.LabelHostname:   name,
+					corev1.LabelHostname:   nodeName,
```
Comment (twz123) [inline pkg/autopilot/controller/setup.go:150]: It's a bit confusing that autopilot stores the _node_ name in the _host_ name label :smile:

File: pkg/autopilot/controller/setup.go [hunk 3]
```diff
@@ -73,23 +75,28 @@ func (sc *setupController) Run(ctx context.Context) error {
 		}
 	}
 
-	hostname, err := apcomm.FindEffectiveHostname()
```
Comment (twz123) [inline pkg/autopilot/controller/setup.go:76]: It would probably be easier to use the same name for the ControlNode object that's used for the Kubernetes Node object. Maybe that's something we can achieve in config-v2.

**Review by twz123 — APPROVED** [review]

File: pkg/autopilot/controller/setup.go (hunk 1 above)
Comment (makhov) [reply pkg/autopilot/controller/setup.go:55]: I decided to parse the args exactly where it was needed.

File: pkg/autopilot/controller/setup.go (hunk 3 above)
Comment (makhov) [reply pkg/autopilot/controller/setup.go:76]: We have `AUTOPILOT_HOSTNAME` env var to override the ControlNode name.

File: pkg/autopilot/controller/setup.go (hunk 2 above)
Comment (makhov) [reply pkg/autopilot/controller/setup.go:150]: Well, currently it's `ControlNode` name instead of the hostname
