### PR TITLE
Fix kube-dns address on dualstack clusters

### LINKED ISSUE #7294: [dual-stack] kube-dns uses IPv4 when primaryAddressFamily is set to IPv6
### Before creating an issue, make sure you've checked the following:

- [x] You are running the latest released version of k0s
- [x] Make sure you've searched for existing issues, both open and closed
- [x] Make sure you've searched for PRs too, a fix might've been merged already
- [x] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
Linux 6.12.0-124.43.1.el10_1.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 11 06:19:32 EDT 2026 x86_64 GNU/Linux
NAME="AlmaLinux"
VERSION="10.1 (Heliotrope Lion)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="10.1"
PLATFORM_ID="platform:el10"
PRETTY_NAME="AlmaLinux 10.1 (Heliotrope Lion)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:10.1"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
VENDOR_NAME="AlmaLinux"
VENDOR_URL="https://almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-10"
ALMALINUX_MANTISBT_PROJECT_VERSION="10.1"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="10.1"
SUPPORT_END=2035-06-01
```

### Version

v1.35.1+k0s.1

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 30.9 GiB (pass)
File system of /var/lib/k0s: xfs (pass)
Disk space available for /var/lib/k0s: 64.8 GiB (pass)
Relative disk space available for /var/lib/k0s: 92% (pass)
Name resolution: localhost: [::1 127.0.0.1] (pass)
Operating system: Linux (pass)
  Linux kernel release: 6.12.0-124.43.1.el10_1.x86_64 (pass)
  Max. file descriptors per process: current: 524287 / max: 524288 (pass)
  AppArmor: unavailable (pass)
  Executable in PATH: modprobe: /sbin/modprobe (pass)
  Executable in PATH: mount: /bin/mount (pass)
  Executable in PATH: umount: /bin/umount (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (is a listed root controller) (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (is a listed root controller) (pass)
    cgroup controller "memory": available (is a listed root controller) (pass)
    cgroup controller "devices": available (device filters attachable) (pass)
    cgroup controller "freezer": available (cgroup.freeze exists) (pass)
    cgroup controller "pids": available (is a listed root controller) (pass)
    cgroup controller "hugetlb": available (is a listed root controller) (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
        CONFIG_IP_VS_SH: Source hashing scheduling: module (pass)
        CONFIG_IP_VS_RR: Round-robin scheduling: module (pass)
        CONFIG_IP_VS_WRR: Weighted round-robin scheduling: module (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connection tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

When deploying with primaryAddressFamily set to IPv6 in dualstack, kube-dns still runs on IPv4. 

```sh
k0s kubectl get svc --all-namespaces -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}Policy: {.spec.ipFamilyPolicy}{"\n"}Families: {.spec.ipFamilies}{"\n"}ClusterIPs: {.spec.clusterIPs}{"\n"}{"\n"}{end}'
```

```
kubernetes
Policy: SingleStack
Families: ["IPv6"]
ClusterIPs: ["2001:db8:2::1"]

kube-dns
Policy: SingleStack
Families: ["IPv4"]
ClusterIPs: ["10.96.0.10"]

metrics-server
Policy: SingleStack
Families: ["IPv6"]
ClusterIPs: [2001:db8:2::4:17b8"]
```

### Steps to reproduce

1. Create k0s file

```yaml
kind: ClusterConfig
spec:
  api:
    address: 2001:db8:f::10
  network:
    primaryAddressFamily: IPv6
    dualStack:
      enabled: true
      IPv6podCIDR: 2001:db8:1::/112
      IPv6serviceCIDR: 2001:db8:2::/112
    provider: kuberouter
    kuberouter:
      extraArgs:
        router-id: generate
        # Force k0s to pass IPv6 in it's service-cluster-ip-range flag
        enable-ipv6: "true"
        service-cluster-ip-range: 2001:db8:2::/112
      rawArgs:
        # Manually set 2nd service-cluster-ip-range flag
        - "--service-cluster-ip-range=10.96.0.0/12"

```

2. Install controller (kubelet-extra-args forces pod <IPv6><IPv4>)

```sh
k0s install controller --enable-worker --no-taints -c /etc/k0s/k0s.yaml --kubelet-extra-args=--node-ip=2001:db8:f::10,172.16.1.10 --start
```

3. Check service IPs

```sh
k0s kubectl get svc --all-namespaces -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}Policy: {.spec.ipFamilyPolicy}{"\n"}Families: {.spec.ipFamilies}{"\n"}ClusterIPs: {.spec.clusterIPs}{"\n"}{"\n"}{end}'
```

### Expected behavior

kube-dns `.spec.ipFamilies` set to IPv6 with IPv6 `.spec.clusterIPs`

<sup>I'd actually expect dualstack but per docs "by default all the services are single stack"</sup>

### Actual behavior

```
kube-dns
Policy: SingleStack
Families: ["IPv4"]
ClusterIPs: ["<AN_IPV6_ADDRESS>"]
```

### Screenshots and logs

k0s kubectl logs -n kube-system -l k8s-app=kube-dns --tail=100

```
maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
.:53
[INFO] plugin/reload: Running configuration SHA512 = a0c06adb3aa41fc5baa9a525a356d4f8e0206ad810f6a0d1f005e63150f4cd85bb682bac617e725b3996ba493aee5bd94a076b3ff9c64726e7e00a033b2ab1ba
CoreDNS-1.14.1
linux/amd64, go1.25.6,
```

### Additional context

kube-dns being on IPv4 is probably what allows some Pods to work with <IPv4><IPv6> but when forcing <IPv6><IPv4> with `--kubelet-extra-args=--node-ip`, things break.

### PR DESCRIPTION
**Pull request by juanluisvaladas**
## Description

Before this DNSAddress always was always set pbased on n.ServiceCIDR even if it was a dualstack cluster and the primaryAddressFamily was IPv6.

Fixes #7294

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [x] Manual test
- [x] Auto test added

## Checklist

- [x] My code follows the style [guidelines](https://docs.k0sproject.io/head/contributors/) of this project
- [x] My commit messages are [signed-off](https://docs.k0sproject.io/head/contributors/github_workflow/)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: pkg/component/controller/workerconfig/reconciler.go [hunk 1]
```diff
@@ -83,10 +83,10 @@ var (
 )
 
 // NewReconciler creates a new reconciler for worker configurations.
-func NewReconciler(k0sVars *config.CfgVars, nodeSpec *v1beta1.ClusterSpec, clientFactory kubeutil.ClientFactoryInterface, leaderElector leaderelector.Interface, konnectivityEnabled, autopilotDisabled bool) (*Reconciler, error) {
+func NewReconciler(k0sVars *config.CfgVars, nodeConfig *v1beta1.ClusterConfig, clientFactory kubeutil.ClientFactoryInterface, leaderElector leaderelector.Interface, konnectivityEnabled, autopilotDisabled bool) (*Reconciler, error) {
```
Comment (twz123) [inline pkg/component/controller/workerconfig/reconciler.go:86]: What's the motivation for this?

Comment (juanluisvaladas) [reply pkg/component/controller/workerconfig/reconciler.go:86]: This is required so that we can call nodeConfig.PrimaryAddressFamily() in line 89.

If you prefer we could add the primary address family as an argument instead.
