### PR TITLE
Use dedicated leasepool for worker config component

### LINKED ISSUE #4450: Autopilot with controller+worker roles fails to update
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
ALL
```

### Version

1.30.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
➡️ Please replace this text with the output of `k0s sysinfo`. ⬅️
</pre>
</details>

### What happened?

When k0s running with controller+worker nodes, autopilot fails to update. Say you have 3 controller+worker nodes. When autopilot updates the first one, it is very likely that the node will lose it's leadership. If it was a leader in the first place.

Now when autopilot updates the k0s binary and restarts it (via systemd/openrc),t he controller parts does start properly. The worker part will NOT start properly as it does not find the `worker-config-default-1.30` configmap. This is because the controller does not apply the new version of the CM as it is not the leader. Hence we reach a "deadlock", autopilot cannot proceed as the first controller does not successfully update.

This doesn't happen 100% of the time, if one is lucky enough that autopilot updates first the controller that is a leader and everything is fast enough so that node does not lose its leadership it will succeed.

### Steps to reproduce

1. Install 3 nodes with controller-worker with version 1.29.4 (the version does not really matter AFAIK)
2. Apply a plan to update to 1.30.0
3. Observe a deadlock

### Expected behavior

Autopilot successfully updates controller+worker nodes

### Actual behavior

Autopilot gets into "deadlock" where the worker part on an updated controller does not start properly unless the updated node happens to also be the leader.

### Screenshots and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jnummelin**
## Description

With this change the first controller on new version can apply the needed versioned resources as it will always be guaranteed to become the leader.

Fixes #4450 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

- [ ] Manual test
- [x] Auto test added

## Checklist:

- [x] My code follows the style [guidelines](https://github.com/k0sproject/k0s/blob/main/docs/contributors/overview.md) of this project 
- [x] My commit messages are [signed-off](https://github.com/k0sproject/k0s/blob/main/docs/contributors/github_workflow.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by makhov — DISMISSED** [review]

File: inttest/ap-controllerworker/controllerworker_test.go [hunk 1]
```diff
@@ -0,0 +1,209 @@
...
+const k0sConfigWithMultiController = `
+spec:
+  api:
+    address: %s
+  storage:
+    etcd:
+      peerAddress: %s
+`
+
+const oldVersion = "v1.29.4+k0s.0"
```
Comment (twz123) [inline inttest/ap-controllerworker/controllerworker_test.go:50]: Eventually, this should probably be dynamic, coming from `hack/tools/gen-matrix.sh`.

**Review by twz123 — APPROVED** [review]
